feat: allow space group access
lightdash/lightdash pull request #10082
Opened 2024-05-15 09:45 UTC by Shifan-Gu

Closes: 
[8718](https://github.com/lightdash/lightdash/issues/8718)

### Description:

https://github.com/lightdash/lightdash/assets/101873365/90e675c0-82e2-4857-bf62-698cbf96dadd

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-05-16 14:34 UTC, rephus commented
Hi @Shifan-Gu there are a few errors with types, could you take a look ?  I'll review the code and test it in the meantime 

![image](https://github.com/lightdash/lightdash/assets/1983672/3104dfcd-a248-4a3b-b3e9-ddd81161f951)

2024-05-16 14:53 UTC, rephus requested changes
The implementation looks good, most of the code seems a copy from projectGroups. There were a few typos on the copy-paste in the controller. 

I'd like to test this once the `type` errors are fixed.

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +     * Grant a user access to a space
```suggestion
     * Grant a group access to a space
```

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +     * @param userUuid The uuid of the user to grant access to
```suggestion
     * @param groupUuid The uuid of the group to grant access to
     * @param spaceRole The role for the group in the space
```

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +     * @parmm spaceUuid The uuid of the space to update
```suggestion
     * @param spaceUuid The uuid of the space to update
```

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +     * Remove a user's access to a space
```suggestion
     * Remove a group's access to a space
```

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +     * @param userUuid The uuid of the user to revoke access from
```suggestion
     * @param groupUuid The uuid of the group to revoke access from
```

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/services/SpaceService/SpaceService.ts
> +        // TODO: check if user can access groups
TODO ?

2024-05-16 14:53 UTC, rephus commented on packages/backend/src/services/SpaceService/SpaceService.ts
> +        // TODO: check if user can access groups
TODO ?

2024-05-16 14:53 UTC, rephus commented on packages/common/src/utils/projectMemberRole.ts
> +    spaceRoles.reduce<SpaceMemberRole | undefined>((highestRole, role) => {
is it not easier to `filter(!undefined).sortBy(SpaceRoleOrder).reverse()[0]`

2024-05-16 15:45 UTC, Shifan-Gu commented
Thank you @rephus ! 
I will work on the commented issue.

2024-05-21 06:48 UTC, rephus reviewed
It woks pretty well, There is only one UI thing we should fix to avoid confusion, but it can be done on a separate ticket

If I add a user , there is a warning message that appears if the user does not have enough `project` permissions to perform actions in the space

![Screenshot from 2024-05-21 08-41-16](https://github.com/lightdash/lightdash/assets/1983672/00448687-71ab-42dd-a7aa-aaa915614bff)

But When I add a group, this message doesn't appear, and I can't make changes in the space (so I don't have edit permissions) 
![Screenshot from 2024-05-21 08-41-35](https://github.com/lightdash/lightdash/assets/1983672/da66b9e8-97dc-4b1a-ad00-c37a0b1d723f)


Apart from that, everything seems to be working fine, and it is backwards compatible.

2024-05-21 10:28 UTC, Shifan-Gu commented
Hi @rephus

I think what's happening for the second case is that you give the viewer group a space editor role, and it overrides the project viewer role so you don't see any warning here.

I will work on this ticket https://github.com/lightdash/lightdash/issues/9539 which would help explain the role and permission lineage.

2024-05-23 07:28 UTC, rephus commented
Sorry, this is taking longer to review because of this change https://github.com/lightdash/lightdash/pull/10082/commits/0d72b169ecdcce95c89c4727afa06783bbfbd69e I need to test everything again. Next time I'd rather do these non-blocking changes on a separate PR

2024-05-23 07:45 UTC, rephus commented
The issue I mentioned hasn't been fixed. I don't get any warnings if the permission is not correct.

![Screenshot from 2024-05-23 09-43-39](https://github.com/lightdash/lightdash/assets/1983672/079118f7-6b39-43c2-88b9-26a59bf42e71)

But let's not fix this here, let's merge as it is and we'll fix it on a separate PR

2024-05-23 07:52 UTC, rephus commented
Another weird UI behaviour, probably caused by the recent change in permissions. 
I can upgrade permissions for indivdiual users in the group, but I can downgrade. 

eg: if The group can `edit` I can't set an idividual user to `viewer`


[Screencast from 23-05-24 09:50:54.webm](https://github.com/lightdash/lightdash/assets/1983672/60979ae1-0e2a-406c-9682-4412c8ead633)

Again, let's not fix it here, I'll create a separate issue.

2024-05-23 07:54 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +     * Remove a user's access to a space
still not done

2024-05-23 07:59 UTC, rephus commented
Waiting for tests to run. I tested manually and it seems good

2024-05-23 10:18 UTC, rephus approved these changes

2024-05-23 10:18 UTC, merged