fix: embedding guide link
lightdash/lightdash pull request #10632
Opened 2024-07-08 09:12 UTC by 12ian34

Fix embedding guide link which was broken

2024-07-08 15:43 UTC, joaoviana requested changes
One suggestion!

2024-07-08 15:43 UTC, joaoviana commented on docs/docs/references/embedding.mdx
> +For more of a deep dive into setting up and using embedding in Lightdash, check out our [`How to embed content` guide](https://docs.lightdash.com/guides/how-to-embed-content).
Can you try this instead @12ian34 ?

```suggestion
For more of a deep dive into setting up and using embedding in Lightdash, check out our [`How to embed content` guide](../guides/how-to-embed-content.mdx).
```

2024-07-09 06:48 UTC, rephus approved these changes
tested , looks good

2024-07-09 08:29 UTC, joaoviana approved these changes

2024-07-09 08:32 UTC, merged