fix: stop relying on slack network errors on frontend, and amend /sla…
lightdash/lightdash pull request #10716
Opened 2024-07-13 13:45 UTC by maxdiplogit

…ck endpoint

Closes: #10473

### Description:

This PR deals with improving developer productivity by not relying on network errors on the Frontend and also not requesting `/slack/channels` endpoint if slack is not enabled.

The `/slack` endpoint now returns with a response object telling if `slackEnabled` is either True or False. In certain components where `useSlackChannels()` was being used, it will only request channels if the `slackEnabled` property is True.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-07-24 09:53 UTC, ZeRego commented on packages/common/src/types/slackSettings.ts
> +    slackEnabled: boolean;
Using 'installed' as it correlates to an organization installing the slack app. We have been using "enabled" terminology when enabling slack or other third party services for the Lightdash instance.

```suggestion
    isSlackInstalled: boolean;
```

2024-07-24 09:55 UTC, ZeRego commented on packages/backend/src/models/SlackAuthenticationModel.ts
> +            // throw new Error(`Could not find slack installation`);
Adding an explicit undefined instead of 'row' so it's easier to read the code. 

```suggestion
            return undefined;
```

2024-07-24 09:55 UTC, ZeRego commented on packages/backend/src/services/SlackIntegrationService/SlackIntegrationService.ts
> +            // );
Remove comment.
```suggestion
```

2024-07-24 09:58 UTC, ZeRego commented on packages/frontend/src/components/SchedulersView/SchedulersView.tsx
> +    const { data: allSlackChannels } = data?.slackEnabled ? useSlackChannels() : { data: [] };
React Hooks must be called in the exact same order in every component render. They cannot be called inside a condition. 

Instead, the hook can have an argument and pass it to `useQuery` hook.

```
return useQuery({
        queryKey,
        queryFn: () => ...,
        enabled: !!isSlackInstalled,
    });
```

2024-07-24 09:59 UTC, ZeRego requested changes
Thank you for the contribution ❤️ 
Left a couple of comments with request changes. Let me know if you have any questions.

2024-07-26 00:24 UTC, maxdiplogit commented
> Thank you for the contribution ❤️ Left a couple of comments with request changes. Let me know if you have any questions.

@ZeRego 
Made the changes as requested. If there are any more changes or any improvements that can be done, please let me know.

Thank you :smile:

2024-08-05 13:38 UTC, IrakliJani commented
hi @maxdiplogit thanks for your contribution!

changes look good. I have a relevant PR https://github.com/lightdash/lightdash/pull/10991/files

I'll rebase my PR on top of your changes and merge both 🙌

2024-08-05 16:50 UTC, maxdiplogit commented
Great @IrakliJani 😄

2024-08-05 17:24 UTC, IrakliJani commented
@maxdiplogit I rebased my changes on top of your changes and resolved conflicts. The only change that I made to your code is that, instead of returning `isInstalled: true`, it now returns `undefined` and checks accordingly.

2024-08-05 17:25 UTC, IrakliJani commented
@maxdiplogit feel free to add comments here -> https://github.com/lightdash/lightdash/pull/10991

2024-08-05 17:59 UTC, maxdiplogit commented
> @maxdiplogit feel free to add comments here -> #10991

@IrakliJani I have reviewed and approved the changes (from my side). 🙌

2024-08-06 09:17 UTC, ZeRego commented
Closing this PR as this work is being tracked in https://github.com/lightdash/lightdash/pull/10991

2024-08-06 09:17 UTC, closed without merging