Add an option to raise errors in `lightdash start-preview`
lightdash/lightdash pull request #11045
Opened 2024-08-07 06:38 UTC by yu-iskw

Closes: https://github.com/lightdash/lightdash/issues/11044

### Description:

We take advantage of `lightdash start-preview` in our workflows of GitHub Actions. Currently, the command returns only the exit code 0 even if the deployment fails. So, I want to add an option to handle whether or not it raises an error.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-08-07 06:44 UTC, yu-iskw commented on packages/cli/src/index.ts
> +    .option('--raise-errors', 'Raise errors if deploy fails', false)
We can alsot use the `--ignore-errors` option as `lightdash deploy`. But, it changes the behaviors of the command. That's why I introduced `--raise-errors` to keep the current behavior.

2024-08-07 09:13 UTC, ZeRego requested changes
A couple of changes required:

- For consistency with `deploy` command, we can use the same option but with a different default:
```
.option('--ignore-errors', 'Allows deploy with errors on compile', true)
``` 
- This option needs to be available for the commands `preview` and `start-preview`
- In the `packages/cli/src/handlers/preview.ts` we can update the `PreviewHandlerOptions` type to have `ignoreErrors: boolean` and remove `ignoreErrors: true,` from all 4 `deploy(...)` cases

2024-08-07 09:28 UTC, yu-iskw commented
@ZeRego thank you for the feedback. I was wondering how we can set it false with the `--ignore-errors` option, if we set the default value `true`. Does `--ignore-errors` option with the default value of `true` work?

I am not sure the feature to negate a boolean option works in our case. Another option can be to declare `--ignore-errors` and `--no-ignore-errors`. But I felt `--no-ignore-errors` looks difficult to understand.

https://www.npmjs.com/package/commander#other-option-types-negatable-boolean-and-booleanvalue
> If you define --foo first, adding --no-foo does not change the default value from what it would otherwise be.

```typescript
program
  .option('--no-sauce', 'Remove sauce')
  .option('--cheese <flavour>', 'cheese flavour', 'mozzarella')
  .option('--no-cheese', 'plain with no cheese')
  .parse();

const options = program.opts();
const sauceStr = options.sauce ? 'sauce' : 'no sauce';
const cheeseStr = (options.cheese === false) ? 'no cheese' : `${options.cheese} cheese`;
console.log(`You ordered a pizza with ${sauceStr} and ${cheeseStr}`);
```

2024-08-07 09:49 UTC, ZeRego commented
>  I was wondering how we can set it false with the --ignore-errors option, if we set the default value true.

We need to add a parser. Here is an example of an option with default `true`:

```
.option(
        '--use-dbt-list [true|false]',
        'Use `dbt list` instead of `dbt compile` to generate dbt manifest.json',
        parseUseDbtListOption,
        true,
    )
```

You would then be able to run ```lightdash start-preview --ignore-errors false```

2024-08-07 09:51 UTC, yu-iskw commented
Alright. I will do refactoring that part. Thanks.

2024-08-07 09:56 UTC, yu-iskw commented
@ZeRego let me clarify one thing. Do we need to change the behavior of `lightdash deploy --ignore-errors` as well? If so, that change might impact some Lightdash users. If not, the consistency between the option on `lightdash deploy` and `lightdash start-preview`.

```
# Need the argument
lightdash start-preview --ignore-errors false

# Don't need the argument
lightdash deploy --ignore-errors
```

2024-08-07 10:25 UTC, ZeRego commented
> @ZeRego let me clarify one thing. Do we need to change the behavior of `lightdash deploy --ignore-errors` as well? If so, that change might impact some Lightdash users. If not, lacks the consistency between the option on `lightdash deploy` and `lightdash start-preview`.
> 
> ```
> # Need the value
> lightdash start-preview --ignore-errors false
> 
> # Don't need the value
> lightdash deploy --ignore-errors
> ```

No changes to deploy. But you are correct, the option name is consistent but the default value would differ between deploy/preview commands and might cause some confusion
We can set default `false` for all of them and I will notify the community about this behaviour change and how to use the option to keep ignoring errors on preview.

2024-08-07 12:08 UTC, yu-iskw commented
@ZeRego I have modified the code. Can you review it again please?

https://github.com/lightdash/lightdash/pull/11045/commits/f265b9b70b4774ac9c536fd38feed0576e7e5e3f

2024-08-07 12:10 UTC, ZeRego commented on packages/cli/src/handlers/preview.ts
> +            ignoreErrors: !options.raiseErrors,
We need to remove `ignoreErrors: !options.raiseErrors,` and `ignoreErrors: true` from all calls to `await deploy(...)`.

2024-08-08 07:28 UTC, yu-iskw commented
@ZeRego Sorry for bothering you. Can you review it again please?

2024-08-08 16:55 UTC, ZeRego approved these changes
lgtm 🙌  

Going to prep an announcement and release this tomorrow morning 🚀

2024-08-09 00:49 UTC, yu-iskw commented
@ZeRego thank you for testing this. I look forward to the release.

2024-08-09 08:40 UTC, merged