Fix first value agg
lightdash/lightdash pull request #11420
Opened 2024-09-05 09:39 UTC by rephus

Closes:  https://github.com/lightdash/lightdash/issues/11329

### Description:

Before

![Screenshot from 2024-09-05 10-46-31](https://github.com/user-attachments/assets/6b23339f-345f-4b46-a58b-d917f7c70dcf)

After

Postgres:

![Screenshot from 2024-09-05 11-04-51](https://github.com/user-attachments/assets/6294f808-317d-436e-88b8-a3575411a6c4)

Bigquery:
![Screenshot from 2024-09-05 10-48-34](https://github.com/user-attachments/assets/d08f28e0-7c22-4716-a195-8dbde256474f)

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-09-05 11:00 UTC, joaoviana approved these changes
Could you pull latest and re-run `yarn generate-api`?

2024-09-05 13:27 UTC, owlas requested changes
This aggregation should be called `any` value otherwise it's not accurate and for databases not supporting "first" it would be confusing.

Instead of the ternary `agg = first ? 'any' : agg` can we have a mapping that maps our internal agg names to the correct functions for each database. It could live on the warehouse clients

2024-09-06 08:45 UTC, owlas commented on packages/common/src/utils/warehouse.ts
> +                    return `(ARRAY_AGG(${q}${reference}${q}))[1]`;
fun workaround!

2024-09-06 08:49 UTC, owlas approved these changes

2024-09-06 09:02 UTC, merged