fix: add field validation to project form
lightdash/lightdash pull request #1145
Opened 2022-01-14 17:22 UTC by ZeRego

### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1121

### Description:

### Preview:

![Screenshot 2022-01-14 at 17 18 18](https://user-images.githubusercontent.com/9117144/149557864-299e5a40-edea-49fd-93b9-43d63bcf7d5d.png)

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

2022-01-14 17:24 UTC, owlas commented on packages/frontend/src/utils/fieldValidators.ts
> +export const hasWhiteSpaces =
@ZeRego is this `hasNoWhiteSpaces`

2022-01-14 17:24 UTC, owlas requested changes
One question

2022-01-14 18:24 UTC, nathaliabj commented on packages/frontend/src/components/ProjectConnection/DbtForms/BitBucketForm.tsx
> +                    hasWhiteSpaces: hasWhiteSpaces('Repository'),
I feel like the naming is a bit confusing here, it sounds like we are expecting for it to have white spaces?

2022-01-17 11:33 UTC, owlas approved these changes

2022-01-17 11:42 UTC, merged