Feat org permissions UI
lightdash/lightdash pull request #1177
Opened 2022-01-19 15:07 UTC by nathaliabj

### Pre requirements:
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: 

### Description:

### Preview:

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

2022-01-20 17:34 UTC, nathaliabj commented
Thinking about what will the non admin users see on the `User management` tab  @PriPatel suggests to remove this option all together for them. 

options are:
- disable this tab when they are non admin
- remove the tab all together
- show a screen saying that they don't have access instead of showing the list of users

@owlas @ZeRego @PriPatel any thoughts? 💭

2022-01-21 09:59 UTC, owlas commented
@nathaliabj sounds good! We can remove the entry in the sidebar if they don't have permission

2022-01-21 16:13 UTC, owlas requested changes
Looks good! Just one thing, Organizations changed from US to British spelling

2022-01-21 16:13 UTC, owlas commented on packages/frontend/src/components/UserSettingsModal/OrganisationPanel/index.tsx
> +const OrganisationPanel: FC = () => {
We usually use US spelling!

2022-01-24 13:57 UTC, owlas approved these changes
lgtm! 🔥

2022-01-24 13:59 UTC, merged