fix: dashboard X spacing to be consistent with headers
lightdash/lightdash pull request #12533
Opened 2024-11-20 15:26 UTC by andrewdw

Closes: #12528 

### Description:
- makes dashboard spacing consistent with headers

![CleanShot 2024-11-20 at 16 23 32](https://github.com/user-attachments/assets/60b7433a-9f51-4937-b345-fe3adbbff5c3)

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-11-21 16:00 UTC, magnew approved these changes
Tested with and without tabs, looks good ✅ 
Code makes sense if we want tabs going to the edges, which it looks like we do ✅

2024-11-21 18:16 UTC, joaoviana commented on packages/frontend/src/pages/Dashboard.tsx
> +                        <Group position="apart" align="flex-start" noWrap>
I believe you can remove the Box above and just have the group like this

```
<Group
                        position="apart"
                        align="flex-start"
                        noWrap
                        grow
                        sx={{
                            overflow: 'auto',
                        }}
                    >


```

2024-11-21 18:17 UTC, joaoviana requested changes
Once PR is rebased, let's wait for the e2es to pass 👍

2024-11-22 10:51 UTC, joaoviana approved these changes
shipit

2024-11-22 10:52 UTC, merged