docs: add row level filtering to tables
lightdash/lightdash pull request #12567
Opened 2024-11-21 14:56 UTC by TuringLovesDeathMetal

Adds references to row-level filtering in the `tables` reference docs (because I couldn't find the docs and went looking here)

2024-11-21 15:13 UTC, jpetey75 commented
@TuringLovesDeathMetal i found this confusing that you use this sentence:
>Using sql_filter with [user attributes](https://deploy-preview-12567--peaceful-bassi-cbf284.netlify.app/references/user-attributes) allows you to set up granular [row-level security in your tables](https://deploy-preview-12567--peaceful-bassi-cbf284.netlify.app/references/user-attributes#row-filtering-with-sql_filter).

Then the example _doesn't_ use attributes, it's just a global SQL filter. 

Maybe put that line about user attributes below the two example code blocks? That way it's like: here's how SQL filter works, and now go check out this add-on to SQL filters that uses attributes for row-level security.

2024-11-21 15:13 UTC, jpetey75 requested changes
@TuringLovesDeathMetal i found this confusing that you use this sentence:
>Using sql_filter with [user attributes](https://deploy-preview-12567--peaceful-bassi-cbf284.netlify.app/references/user-attributes) allows you to set up granular [row-level security in your tables](https://deploy-preview-12567--peaceful-bassi-cbf284.netlify.app/references/user-attributes#row-filtering-with-sql_filter).

Then the example _doesn't_ use attributes, it's just a global SQL filter. 

Maybe put that line about user attributes below the two example code blocks? That way it's like: here's how SQL filter works, and now go check out this add-on to SQL filters that uses attributes for row-level security.

2024-11-21 15:19 UTC, TuringLovesDeathMetal commented
ya, agreed - I switched it at the last minute. But have switched it back and added an example!

2024-11-25 11:41 UTC, jpetey75 approved these changes

2024-11-25 23:26 UTC, merged