feat: add delete project
lightdash/lightdash pull request #1567
Opened 2022-03-22 14:30 UTC by rephus

WIP

### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1561

### Description:
Add delete button on list of projects, and build the backend endpoint 

### Preview:

![image](https://user-images.githubusercontent.com/1983672/159505556-c12d93c3-3dd9-4ffd-b304-8b5289fed73f.png)

### Scope of the changes (select all that apply):
- [x] Frontend  
- [x] Backend  
- [ ] Common  
- [ ] E2E tests  
- [x] Docs  
- [ ] CI/CD

2022-03-22 16:28 UTC, rephus commented
![image](https://user-images.githubusercontent.com/1983672/159524333-9bd248fc-b447-4f10-8e58-984b7f2b74fb.png)

2022-03-23 10:14 UTC, ZeRego commented on packages/backend/src/routers/organizationRouter.ts
> +    isAuthenticated,
We should also add `unauthorisedInDemo,` to block this route for demo deployments.

2022-03-23 10:21 UTC, ZeRego requested changes

2022-03-23 10:21 UTC, ZeRego commented on packages/backend/src/services/ProjectService/ProjectService.ts
> +        } */
We can remove this now that we agree we want to allow users to delete all projects

2022-03-23 10:21 UTC, ZeRego commented on packages/backend/src/services/ProjectService/ProjectService.ts
> +            await runningAdapter.destroy();
We can also delete the adapter from memory, just to be sure it's all cleaned. 
``` delete  this.projectAdapters[projectUuid];```

2022-03-23 10:21 UTC, ZeRego commented on packages/common/src/index.ts
> +
Is this type used somewhere?

2022-03-23 11:00 UTC, rephus commented
tested latest version using rest-client on vs code (list -› delete -> list ) 

![Mar-23-2022 11-58-53](https://user-images.githubusercontent.com/1983672/159684691-2a7bbbcc-930b-403b-8f83-07d4a4c41ea6.gif)

2022-03-23 12:47 UTC, rephus commented
openapi docs: 
* Deletion
![image](https://user-images.githubusercontent.com/1983672/159702493-428d6d5a-e893-4092-b265-921e32433163.png)

* List of projects , it was missing 
![image](https://user-images.githubusercontent.com/1983672/159702632-3d7f1476-c441-4c67-8d5d-398a03dfc19d.png)

2022-03-23 14:08 UTC, ZeRego approved these changes
lgtm 🎉  we just need to wait for the FE changes before merging

2022-03-24 07:56 UTC, rephus commented
Tested once more after merging frontend. 

All good to go 🚀

2022-03-24 09:41 UTC, owlas approved these changes
Looks great! awesome job

2022-03-24 09:42 UTC, merged