feat: add new round meta tag on dbt schema
lightdash/lightdash pull request #1586
Opened 2022-03-25 08:54 UTC by rephus

### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1390

### Description:
Added a new `round`meta on dbt schema that will round the number in SQL 

![image](https://user-images.githubusercontent.com/1983672/160088011-712820b3-c2bd-4389-a8cf-16014fc94a93.png)

### Preview:
![Mar-25-2022 09-43-39](https://user-images.githubusercontent.com/1983672/160087628-daef2930-f59a-48db-8464-9a6a279151c9.gif)

Before: 
![image](https://user-images.githubusercontent.com/1983672/160087949-397f1e86-98a4-413a-acee-c75e74786578.png)

After: 
![image](https://user-images.githubusercontent.com/1983672/160087878-703a164a-c6c1-4c8b-aeb0-e35929ad59de.png)

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [x] Backend  
- [x] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

2022-03-25 08:55 UTC, rephus commented on packages/backend/src/exploreCompiler.ts
> +    let renderedSql = metric.sql.replace(lightdashVariablePattern, (_, p1) =>
I was not too sure if it is cleaner to do it this way, or wrap this function inside a compileMetricRoundSql function or something.

Let me know what's your preference

2022-03-25 08:56 UTC, rephus commented on packages/backend/src/exploreCompiler.ts
> +    if (metric.round) renderedSql = `ROUND(${renderedSql}, ${metric.round})`;
`ROUND` needs to be executed after the SQL operation like `ROUND(AVG(x), 2)` . 

This will not work: `AVG(ROUND(x,2))

2022-03-25 09:01 UTC, ZeRego requested changes
This is looking good :) We should also support this for dimensions. 
Also, do we need to support this for dbt metrics ? @TuringLovesDeathMetal @owlas

2022-03-25 09:22 UTC, rephus commented
> We should also support this for dimensions. 
Are there any examples about dimensions ?

2022-03-25 09:43 UTC, TuringLovesDeathMetal commented
> Also, do we need to support this for dbt metrics ? 
I'd say yes! If it's not too tricky :) Would be great to not build up too much tech debt around supporting dbt metrics to the same level as Lightdash metrics. 

> Are there any examples about dimensions ?

@rephus not sure what you mean? But I'll take a stab:

For example, if I have a dimension called `revenue` and it had values like:
`[3478950, 54738209, 4849329, 4839292, 4839328]` 

I might want to round it to the nearest thousand (`ROUND(revenue, -3)`), so it looked like: 
`[3478000, 54738000, 48493000, etc.]`

2022-03-25 09:45 UTC, ZeRego commented
What happens if we round a dimension/metric that isn't of type number ? 🤔

2022-03-25 09:46 UTC, TuringLovesDeathMetal commented
> What happens if we round a dimension/metric that isn't of type number ? 🤔

It should break. 

This should cause an error. 

Eventually, when we have some way of linting your code, we'd tell you that you can't do this. But for now, it should break if you try to round non-numerics.

2022-03-25 10:38 UTC, rephus commented
Applied also to dimensions

![image](https://user-images.githubusercontent.com/1983672/160105146-231eb707-8434-4786-afcc-cc0b1e54f022.png)

![image](https://user-images.githubusercontent.com/1983672/160105177-7cb3fde7-7164-46b3-8546-79ea12f1fee6.png)

2022-03-25 10:43 UTC, rephus commented
> > What happens if we round a dimension/metric that isn't of type number ? 🤔
> 
> It should break.

This is how the error looks like 
![image](https://user-images.githubusercontent.com/1983672/160106284-dcf69400-8eff-4bed-8bb6-cbe18f48db29.png)

2022-03-25 12:24 UTC, rephus commented
Added docs @TuringLovesDeathMetal 

![image](https://user-images.githubusercontent.com/1983672/160120130-2ca2bcf3-6c50-433b-9f3b-4bedc7945713.png)

![image](https://user-images.githubusercontent.com/1983672/160120151-bd4af3a0-21bf-4f2f-a8df-292b21095e8a.png)

2022-03-25 13:25 UTC, TuringLovesDeathMetal commented
> > > What happens if we round a dimension/metric that isn't of type number ? 🤔
> > 
> > 
> > It should break.
> 
> This is how the error looks like ![image](https://user-images.githubusercontent.com/1983672/160106284-dcf69400-8eff-4bed-8bb6-cbe18f48db29.png)

Could we make this even more obvious? Maybe something like: `function round(blah blah) does not exist. Rounding can only be applied to numeric values.`

2022-03-25 13:50 UTC, rephus commented
> > > > What happens if we round a dimension/metric that isn't of type number ? 🤔
> > > 
> > > 
> > > It should break.
> > 
> > 
> > This is how the error looks like ![image](https://user-images.githubusercontent.com/1983672/160106284-dcf69400-8eff-4bed-8bb6-cbe18f48db29.png)
> 
> Could we make this even more obvious? Maybe something like: `function round(blah blah) does not exist. Rounding can only be applied to numeric values.`

I think this error is coming from SQL , so it is not trivial to change the error message

2022-03-28 09:03 UTC, TuringLovesDeathMetal approved these changes
Looks great!

One related ticket that I opened around adding this to the `project.compiled` tracking event here: https://github.com/lightdash/lightdash-internal-work/issues/239

2022-03-28 09:16 UTC, rephus commented
Added commit to fix: #240

![image](https://user-images.githubusercontent.com/1983672/160366672-a6cce7ee-f370-4842-b295-319614634006.png)

2022-03-28 09:27 UTC, ZeRego approved these changes

2022-03-28 09:45 UTC, owlas commented
@rephus did you mean issue 240 on another repository?

2022-03-28 09:51 UTC, merged