test: dashboard test
lightdash/lightdash pull request #1831
Opened 2022-04-20 16:12 UTC by rephus

### Pre requirements:
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Scope of the changes (select all that apply):
- [ ] Frontend  
- [ ] Backend  
- [ ] Common  
- [x] E2E tests  
- [ ] Docs  
- [ ] CI/CD  

![Peek 2022-04-21 10-02](https://user-images.githubusercontent.com/1983672/164408678-d9fc3bb2-bdc2-499d-a4c5-3b955d7f27bc.gif)

On errors: 

![Screenshot from 2022-04-21 09-36-37](https://user-images.githubusercontent.com/1983672/164408956-38261efb-55a6-4491-8818-d6d6f44cf559.png)

2022-04-21 15:05 UTC, ZeRego requested changes
Thanks for writing more e2e tests 🙌  🥳 

Left a couple of comments + I think we should rebase this branch since we already merged the reset-db script to main.

2022-04-21 15:05 UTC, ZeRego commented on packages/e2e/cypress/integration/dashboard.spec.ts
> +        });
This is great! 😃 
We could have this for all the tests if we define it in the `cypress/support/index.js` ( [blog post explaining](https://ashley-sinner.medium.com/cypress-index-support-file-write-once-run-everywhere-4106c297a1aa) )

2022-04-22 15:17 UTC, rephus commented
I had to migrate and seed again on render to get it to work... it was not a problem of my e2e test . In fact, the e2e test was catching the issue !!!

2022-04-22 15:29 UTC, rephus commented
Finally !!! 
![image](https://user-images.githubusercontent.com/1983672/164746263-096df48e-89de-448e-8e6d-90855d412898.png)

2022-04-22 15:34 UTC, ZeRego approved these changes

2022-04-25 06:17 UTC, merged