feat: add message and button to create new charts when none are saved
lightdash/lightdash pull request #1975
Opened 2022-05-03 16:25 UTC by nathaliabj

### Pre requirements:
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #1674 

### Description:
This PR adds a message and run a query button when there are no available charts in the saved charts section

### Preview:
![Screenshot 2022-05-04 at 13 58 10](https://user-images.githubusercontent.com/31137824/166686658-eb9471e7-066f-47ba-baa9-44b0933724bc.png)
![Screenshot 2022-05-04 at 13 58 02](https://user-images.githubusercontent.com/31137824/166686663-65d87b0e-49c2-4953-884d-10a02bf3bed6.png)

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

2022-05-04 06:34 UTC, rephus approved these changes
Code looks good

2022-05-04 06:36 UTC, owlas requested changes
There is something odd happening on an empty dashboard: https://lightdash-pr-1975.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/dashboards/9cef99de-1c44-4551-a18b-b03b42835d57

An empty state flashes with a "run query" action and then a different empty state shows.
https://user-images.githubusercontent.com/11660098/166632670-b43a5118-76d8-4273-ab7a-5bf57759bc71.mov

2022-05-04 06:36 UTC, owlas commented on packages/frontend/src/components/DashboardTiles/EmptyStateNoTiles/index.tsx
> +const NoSavedChartsAvailable = ({ isChart = false }) => (
We can make this two components, one specifically for charts and one for dashboards. There won't be much duplicate code.

2022-05-04 06:36 UTC, owlas commented on packages/frontend/src/pages/Dashboard.tsx
> +                {dashboardTiles.length <= 0 && <EmptyStateNoTiles />}
This only flashes up, what's the expected behaviour?

2022-05-04 06:36 UTC, rephus commented
I still can't remove charts from the chart list U_U 
<img width="723" alt="image" src="https://user-images.githubusercontent.com/1983672/166632919-81a43c05-a447-4699-8e06-34937854cc9d.png">

2022-05-04 06:41 UTC, rephus commented
<img width="801" alt="image" src="https://user-images.githubusercontent.com/1983672/166633447-d86e70da-d26e-4e37-a24a-2e4ef0b5d7f1.png">
on /home

2022-05-05 10:52 UTC, rephus commented
The test is failing because the `jaffle dashboard` is gone on your Render ... You could try restoring the data on `render shell` ... if it works locally, then I'm that is enough for me.

2022-05-05 10:54 UTC, merged