feat: add min-max switch button and fields
lightdash/lightdash pull request #2175
Opened 2022-05-19 16:56 UTC by nathaliabj

### Pre requirements:
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/lightdash/lightdash/blob/main/.github/CONTRIBUTING.md#sending-a-pull-request).

### Reference:
Closes: #84 

### Description:
This PR adds a min and max value for y-axis

TODO: 
- [ ] Update the values in the chart
- [ ] Update BE to take the new values on a saved chart
- [ ] Add default min/max values/
- [ ] Add tracking

### Preview:
<img width="459" alt="Screenshot 2022-05-19 at 17 34 31" src="https://user-images.githubusercontent.com/31137824/169355792-d4acacd8-017a-4338-8648-3d540b4a78ca.png">

### Scope of the changes (select all that apply):
- [x] Frontend  
- [ ] Backend  
- [ ] Common  
- [ ] E2E tests  
- [ ] Docs  
- [ ] CI/CD

2022-05-24 13:50 UTC, ZeRego requested changes

2022-05-24 13:50 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +    console.log({ resultsData, dirtyLayout });
forgotten console log

2022-05-24 13:50 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +                label={`Auto ${axis}-axis range`}
This label will be inconsistent when axis are flipped

2022-05-24 13:50 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +    const [isAuto, setIsAuto] = useState<boolean>(true);
Fyi: we have a useToggle hook for situations like this that might simplify the code slightly.

The isAuto is `true` every time we load the component. Should the value depend if there is a min/max value and remove the min/max values when user clicks back to be auto ?

2022-05-24 13:50 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +const AxisMinMax: FC<MinMaxProps> = ({ minVal, maxVal, index, axis }) => {
What you think if this component was "dumber" ? it wouldn't depend on `useVisualizationContext` or have axis logic: 
```
interface MinMaxProps {
    label: string;
    min:  string | number | undefined;
    max:  string | number | undefined;
    setMin: (index: number, value: string | number | undefined) => void;
    setMax: (index: number, value: string | number | undefined) => void;
}
```
Use:

```
<AxisMinMax
         label={`Auto ${dirtyLayout?.flipAxes ? 'X' : 'Y'}-axis range (${dirtyLayout?.flipAxes ? 'bottom' : 'left'})`}
         min={dirtyEchartsConfig?.yAxis?.[0]?.min}
         max={dirtyEchartsConfig?.yAxis?.[0]?.max}
         setMin={setYMinValue}
         setMax={setYMaxValue}
/>
```

2022-05-24 13:50 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +                            onBlur={(e) => minVal(index, e.currentTarget.value)}
Isn't the value always string and eCharts supports a number as string "5" ? if so, should we only support min/max property as `string | undefined` ?

2022-05-24 13:52 UTC, ZeRego commented on packages/frontend/src/hooks/useEcharts.ts
> +                    validCartesianConfig?.eChartsConfig?.xAxis?.[0]?.min ||
I believe we need to use `yAxisConfiguration` and `xAxisConfiguration` variables so it works when the axis are flipped.

2022-05-24 15:32 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +const AxisMinMax: FC<MinMaxProps> = ({ minVal, maxVal, index, axis }) => {
The AxisMinMax component shouldn't care about the index if is a ""dumb" component, that should be applied outside 

```
<AxisMinMax
         label={`Auto ${dirtyLayout?.flipAxes ? 'X' : 'Y'}-axis range (${dirtyLayout?.flipAxes ? 'bottom' : 'left'})`}
         min={dirtyEchartsConfig?.yAxis?.[0]?.min}
         max={dirtyEchartsConfig?.yAxis?.[0]?.max}
         setMin={(newValue: string | undefined ) => setYMinValue(0, newValue)}
         setMax={(newValue: string | undefined ) => setYMaxValue(0, newValue)}
/>
```

2022-05-25 09:55 UTC, hamzahc1 commented
@nathaliabj When I tried the preview env, the min-max switch + fields shows up for all types (not just numbers) but you can only input numbers right now. This means it doesn't work for things like dates, strings etc, in those cases should the ranges be disabled for now? 

Also - in this example the chart config showed me 2 x-axis configs... although actually there's only one on the chart. and manually changing the ranges didn't change the charts:
![Screenshot 2022-05-25 at 10 53 59](https://user-images.githubusercontent.com/14341285/170235550-bbe50e71-5508-4cd6-9f99-a804493b2dbe.png)

2022-05-25 10:38 UTC, TuringLovesDeathMetal commented
@nathaliabj just popping this here for transparency!

We said, priorities of things to change:

1. These `range` options should only appear when the values are _**numeric**_
2. There should be no `x-axis` option (only y-axis option). Except on horizontal bar charts (where there's an `x-axis` option, but no `y-axis` option)

Otherwise, I'm going to keep playing around with it and see what else I can spot 👀

2022-05-25 10:41 UTC, PriPatel commented
> The right-axis range keeps popping up (even if there's no right-axis)
This is not a bug! We left it there because it was taking hours to fix. 
@ZeRego this is the thing we tried to address when working on chart config but its quite complex, correct?

2022-05-25 10:43 UTC, ZeRego commented
> > The right-axis range keeps popping up (even if there's no right-axis)
> 
> This is not a bug! We left it there because it was taking hours to fix. @ZeRego this is the thing we tried to address when working on chart config but its quite complex, correct?

If we are talking about the second y axis configuration inputs, that is correct.

2022-05-25 11:05 UTC, TuringLovesDeathMetal commented
> This is not a bug! We left it there because it was taking hours to fix.

hmmm...this definitely feels like a bug. (but it may be an intentional bug haha). 

@ZeRego is this impossible? Or just hard to do?

2022-05-25 15:08 UTC, TuringLovesDeathMetal commented
@ZeRego the default range is always min = 0 (not min = min value). This was specified in the ticket, but I'm not sure if it's a massive change? (if yes, we can create a new ticket for it)

E.g. here, I would expect that the min value by default would be the min value in the chart (30), not 0

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/31848148/170295618-4e24437a-862a-40e0-a600-d6d8176b71a9.png">

2022-05-25 15:12 UTC, merged