feat: inverse x chart values chartconfig
lightdash/lightdash pull request #2901
Opened 2022-08-09 09:12 UTC by rephus

Closes: #2878

### Description:

![Peek 2022-08-09 11-06](https://user-images.githubusercontent.com/1983672/183611579-427d1557-a7ab-4c98-be30-9e904f8993b9.gif)

2022-08-09 14:30 UTC, owlas requested changes
The form doesn't persist my value:

![Aug-09-2022 15-29-28](https://user-images.githubusercontent.com/11660098/183675600-aa1bdc21-67d2-4f47-8019-32c7b6767a95.gif)

2022-08-10 13:00 UTC, rephus commented
> Nice find on the `inverse` option!
> 
> Could we make this a toggle switch instead of a dropdown with two options.
> 
> It could be: `Invert axis? true/false`

I had a chat with @PriPatel and we decided to use dropdown

2022-08-10 13:02 UTC, rephus commented
> The form doesn't persist my value:
> 
> ![Aug-09-2022 15-29-28](https://user-images.githubusercontent.com/11660098/183675600-aa1bdc21-67d2-4f47-8019-32c7b6767a95.gif) [ ![Aug-09-2022 15-29-28](https://user-images.githubusercontent.com/11660098/183675600-aa1bdc21-67d2-4f47-8019-32c7b6767a95.gif) ](https://user-images.githubusercontent.com/11660098/183675600-aa1bdc21-67d2-4f47-8019-32c7b6767a95.gif) [ ](https://user-images.githubusercontent.com/11660098/183675600-aa1bdc21-67d2-4f47-8019-32c7b6767a95.gif)

mmm, it works for me on render https://lightdash-pr-2901.onrender.com/projects/3675b69e-8324-4110-bdca-059031aa8da3/tables/orders

are you doing anything special ?

2022-08-11 10:26 UTC, ZeRego commented
@rephus I was also able to replicate the bug where the value isn't kept. 
![bug](https://user-images.githubusercontent.com/9117144/184113904-d9b6cd4c-fa2f-45a8-8396-13a8b6d8d2d4.gif)

2022-08-11 10:29 UTC, ZeRego commented on packages/frontend/src/components/ChartConfigPanel/ChartConfigTabs.tsx
> +                                    defaultValue="ascending"
The bug is probably because we set `defaultValue` instead of `value` with the value from the config

2022-08-11 11:49 UTC, ZeRego approved these changes

2022-08-11 11:50 UTC, ZeRego approved these changes

2022-08-11 12:57 UTC, merged