fix: table config whith columns that arent in the results
lightdash/lightdash pull request #3011
Opened 2022-08-19 11:35 UTC by ZeRego

Closes: #2983 

### Description:

2022-08-22 08:48 UTC, rephus commented
E2E test failed, related ? 
![image](https://user-images.githubusercontent.com/1983672/185879967-46c54e78-8e8f-4591-aabf-5e4842590f72.png)

2022-08-22 09:24 UTC, rephus requested changes
Fix E2E

2022-08-23 07:58 UTC, rephus commented
@owlas while you are working this, could you confirm if this change fixes https://github.com/lightdash/lightdash/issues/3039 too ?

2022-08-23 09:58 UTC, rephus commented
Sounds like this one is also affected by this bug: https://github.com/lightdash/lightdash/issues/3055 /cc @owlas

2022-08-23 14:25 UTC, owlas commented
Yep on it! Think I've got the solution.

Targeting: #2983 #3039 #3055

2022-08-24 14:17 UTC, rephus commented
build is failing

2022-08-24 14:21 UTC, rephus reviewed
I tested it and everything looks alright . Nice job !

I didn't notice any performance issues. 

Once you fix the build you can merge

2022-08-24 14:21 UTC, rephus commented on packages/frontend/src/components/TableConfigPanel/ColumnConfiguration.tsx
> +    console.log(selectedItemIds);
Leftover console log

2022-08-24 14:25 UTC, rephus commented
I noticed a bug: column names are empty on table config
![image](https://user-images.githubusercontent.com/1983672/186443825-81a91387-6638-433b-ba86-e12c67f1e623.png)

2022-08-24 14:41 UTC, owlas commented
I managed to reproduce all 3 bugs above on main. But they're all fixed in this branch

2022-08-24 15:08 UTC, rephus commented
Pivoted tables does not use  the new table header format... 
![image](https://user-images.githubusercontent.com/1983672/186454467-c64aed8f-b755-416d-b1d6-47d450ebe60e.png)

I'm happy to tackle this on a separate PR

2022-08-24 15:12 UTC, rephus approved these changes
Everything looks good, I can't find any bugs and this is solving the 3 open tickets , so I'm happy to merge this.

2022-08-24 15:14 UTC, owlas commented
Great! Will wait for e2e

2022-08-24 15:27 UTC, merged