feat: remove hidden tables toggle
lightdash/lightdash pull request #3347
Opened 2022-09-29 21:46 UTC by owlas

Closes: #3322 

### Description:

Removes the option to show all tables in the UI

2022-09-29 21:55 UTC, hamzahc1 commented
Do you think there should be a prompt on the explore view (similar to sql runner) saying "missing tables?" that links them to the tables config page in the settings?

2022-09-30 09:17 UTC, ZeRego requested changes
ps: You deleted the events.yml file by mistake.

2022-09-30 09:17 UTC, ZeRego commented on packages/backend/src/routers/projectRouter.ts
> -                req.query.filtered === 'true',
This is going to break the project table configuration page (ProjectTablesConfiguration) where it expects to get all the tables.

2022-09-30 10:56 UTC, owlas commented
I don't think that prompt will be relevant very often so I wouldn't want to add more things to the explorer page, where pixels are at a premium!

2022-09-30 13:22 UTC, ZeRego commented
Closing in favour of #3357

2022-09-30 13:22 UTC, closed without merging