feat: share short urls
lightdash/lightdash pull request #3428
Opened 2022-10-07 14:53 UTC by rephus

Closes: 

### Description:

2022-10-11 12:11 UTC, rephus commented on packages/backend/src/services/ShareService/ShareService.ts
> +    async createShareUrl(path: string, params: string): Promise<ShareUrl> {
![Screenshot from 2022-10-11 14-09-25](https://user-images.githubusercontent.com/1983672/195086100-67bfc3d4-28e7-49c0-9329-56fc7ba6fb49.png)

2022-10-11 12:19 UTC, rephus commented on packages/backend/src/database/entities/share.ts
> +    params: string;
![Screenshot from 2022-10-11 14-07-11](https://user-images.githubusercontent.com/1983672/195087693-08331b76-0a91-4cb3-9e85-ed6aeb1dbe43.png)

![Screenshot from 2022-10-11 14-17-55](https://user-images.githubusercontent.com/1983672/195087712-452eaf32-55ea-4d12-b7d5-e3cf66780250.png)

2022-10-11 12:56 UTC, ZeRego commented on packages/backend/src/database/entities/share.ts
> +    params: string;
Missed `created_at` in this type

2022-10-11 13:01 UTC, ZeRego requested changes

2022-10-11 13:01 UTC, ZeRego commented on packages/backend/src/services/ShareService/ShareService.ts
> +        const shareUrl = await this.shareModel.getSharedUrl(nanoid);
This permission check should check against the shareUrl org uuid

2022-10-11 13:01 UTC, ZeRego commented on packages/backend/src/models/ShareModel.ts
> +            .select<ShareUrl[]>('*');
We will have to join user and org tables to return the uuids.

2022-10-11 13:55 UTC, rephus commented on packages/backend/src/database/entities/share.ts
> +    params: string;
What do you mean ?

2022-10-11 14:10 UTC, ZeRego commented on packages/backend/src/database/entities/share.ts
> +    params: string;
We have a `created_at` column but is not part of the type  `DbShareUrl`

2022-10-11 14:12 UTC, ZeRego approved these changes
lgtm 🚀

2022-10-11 15:16 UTC, rephus commented
Not sure what's wrong with render. retesting here https://github.com/lightdash/lightdash/pull/3466

2022-10-12 06:23 UTC, rephus commented
Merged https://github.com/lightdash/lightdash/pull/3466

2022-10-12 06:23 UTC, closed without merging

2022-10-12 07:05 UTC, rephus commented
@12ian34 this is cool headway material

2022-10-12 15:18 UTC, 12ian34 commented
cc @hamzahc1