feat: reference lines
lightdash/lightdash pull request #3960
Opened 2022-12-09 11:02 UTC by rephus

Closes: #3380

### Description:

[Screencast from 09-12-22 11:56:50.webm](https://user-images.githubusercontent.com/1983672/206688028-8e2f34db-a72c-4979-a123-a32a74318913.webm)

2022-12-09 13:58 UTC, hamzahc1 commented
@rephus I know this is a draft but watching your video, do you need both "horizontal/vertical" and a field input? Depending on the field you select, wouldn't the line be either vertical or horizontal based on the axis I've chosen to have that field on?

2022-12-09 14:20 UTC, rephus commented
> @rephus I know this is a draft but watching your video, do you need both "horizontal/vertical" and a field input? Depending on the field you select, wouldn't the line be either vertical or horizontal based on the axis I've chosen to have that field on?

Yes @hamzahc1 ! you are right, @TuringLovesDeathMetal  and I decided to reduce the scope of this feature, so at the beggining we will only allow 1 reference line, this ticket https://github.com/lightdash/lightdash/issues/3959 should allow multiple lines .

2022-12-09 14:30 UTC, hamzahc1 commented
Ah ok - what I actually mean though is in terms of the UX - if  I select a field to add a reference line, if that field is on the x-axis, then the line is going to plot vertically and if i select a different field that happens to be on the y-axis, then it's going to plot horizontally. 

So the step should be:
- Select field 
- Select value
- Line appears (since we already know the orientation based on the field we don't need to ask if it's vertical or horizontal in the UI)

2022-12-09 14:36 UTC, rephus commented
> Ah ok - what I actually mean though is in terms of the UX - if I select a field to add a reference line, if that field is on the x-axis, then the line is going to plot vertically and if i select a different field that happens to be on the y-axis, then it's going to plot horizontally.


AHhh, I understand the confusion now !!. The `horizontal` is part of the `legend` option, not part of this Reference Line. The UI looks like this. 

![image](https://user-images.githubusercontent.com/1983672/206725868-91824c4f-57c1-4e63-adb9-bcbb02d7fb74.png)

And yes, it works exactly as you described it.

2022-12-09 15:25 UTC, rephus commented
## Interesting edge case /limitation: 

@TuringLovesDeathMetal FYI 

IF you have multiple series on the same axis , the line will appear in whatever value is displayed, not in the value for the field...
For example I have `order amount` and `fulfillment rate` both on the same "left" Yaxis (but they are on a different scale) 
![image](https://user-images.githubusercontent.com/1983672/206734936-0cf7a628-c244-46de-855f-a0415f299cab.png)


IF I select 0.7 (70%) the value will appear on the 0.7 of `order amount` , like this: 
![image](https://user-images.githubusercontent.com/1983672/206735411-87c01926-3376-42a6-bca7-ff20b9f65985.png)

The solution will be to move it to another axis (eg: right) 

![image](https://user-images.githubusercontent.com/1983672/206734694-d8ff3bb3-a0d6-489f-8f54-830de87afc0d.png)

2022-12-09 15:27 UTC, rephus commented on packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLines.tsx
> +                    <InputGroup
The reason why I'm using an InputGroup isntead of a NumericInput is because I want to type `decimal` numbers (for %) not just integers.

2022-12-09 15:33 UTC, rephus commented on packages/frontend/src/components/ChartConfigPanel/Legend/ReferenceLines.tsx
> +                const series = dirtyEchartsConfig?.series.map((serie) => {
Once we have multiple reference lines, we can replace this `reset` and updateAll with a updateSingleSeries

2022-12-09 16:04 UTC, TuringLovesDeathMetal commented
@rephus I think that's fine for the edge case! 

I'd expect people to add a secondary axis anyways if they were looking to have two metrics that have really different scales on the same plot :)

2022-12-09 16:07 UTC, TuringLovesDeathMetal requested changes
@rephus this is super exciting 😍 

Three things:

1. Can we make the line default to black instead of blue and make the line width a bit thicker? Otherwise it doesn't show up on our default chart colours:
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/31848148/206743512-83aa0e29-d77b-4d77-8800-30b9f7fa6cee.png">


2. Can we change the `legend` tab to be called `display`? 

3. Can we remove the arrow head? I get that the reference line is "going to infinity" but I find it looks a bit weird 🤔 (unless you really like it! Then we can keep it - it's definitely subjective 😅 )

2022-12-09 16:10 UTC, hamzahc1 commented
Was also going to ask to remove the arrowhead 🫣

2022-12-09 21:25 UTC, rephus commented
Yep, I agree @TuringLovesDeathMetal @hamzahc1. how about this ? 

![image](https://user-images.githubusercontent.com/1983672/206798547-30853128-6112-474c-b766-9c25843cc5ea.png)

```
symbol: 'none', 
lineStyle: {
          color: '#000',
          width: 3,
          type: 'solid',
      }
                                ```

2022-12-12 15:56 UTC, TuringLovesDeathMetal approved these changes
looks great!

2022-12-16 08:31 UTC, merged