chore: improve forbidden error message
lightdash/lightdash pull request #4076
Opened 2023-01-03 16:59 UTC by ZeRego

Closes: #3835 

### Description:

Changes:
- improve default message for Forbidden and Authorization errors
- create a generic component that handles all types of Lightdash errors

Error on space page
![Screenshot 2023-01-03 at 16 51 43](https://user-images.githubusercontent.com/9117144/210404070-019d3e0f-0e4f-4ada-80a4-f37478eae8e9.png)

Error on chart page
![Screenshot 2023-01-03 at 16 52 13](https://user-images.githubusercontent.com/9117144/210404084-3a45b4a9-6cc1-404c-9bda-c402ad6ad4bd.png)

Error on dashboard page
![Screenshot 2023-01-03 at 16 52 54](https://user-images.githubusercontent.com/9117144/210404096-e0deace3-24ff-43fa-a972-adbd1de19218.png)

2023-01-03 17:03 UTC, IrakliJani reviewed
nice cleanup.
we use nonideal state with error message over and over in other places as well. maybe update those too?

<img width="476" alt="CleanShot 2023-01-03 at 21 02 39@2x" src="https://user-images.githubusercontent.com/962095/210405041-84d5dea8-ca8e-4e90-b4d2-afb70f5ebf75.png">

2023-01-03 17:03 UTC, IrakliJani commented on packages/frontend/src/components/common/Error/index.tsx
> +            console.log('error', error);
extra

2023-01-04 08:10 UTC, TuringLovesDeathMetal requested changes
@ZeRego looks great! thanks for improving this ❤️ 

Two things:
1. Will we use teh same dashboard/chart access error messages if one day we let people limit access to specific charts/dashboards (not just the spaces they're in)? If yes, then maybe we change the error message to: `You don't have access to this chart/dashboard` (instead of talking about the spaces they're in). If no, then I quite like how specific/helpful it is! So I'd keep it :) 
2. Can we change the first error message, it reads a bit funny 🙏 So, `You don't have access to this resource or action.` (instead of `you have no`...)

2023-01-04 13:48 UTC, ZeRego commented
> @ZeRego looks great! thanks for improving this ❤️
> 
> Two things:
> 
> 1. Will we use teh same dashboard/chart access error messages if one day we let people limit access to specific charts/dashboards (not just the spaces they're in)? If yes, then maybe we change the error message to: `You don't have access to this chart/dashboard` (instead of talking about the spaces they're in). If no, then I quite like how specific/helpful it is! So I'd keep it :)
> 2. Can we change the first error message, it reads a bit funny 🙏 So, `You don't have access to this resource or action.` (instead of `you have no`...)

1. Yes, the messages will be different. 
2. fixed :)

2023-01-05 09:01 UTC, TuringLovesDeathMetal approved these changes
Nice! Looks great :)

2023-01-05 15:32 UTC, IrakliJani approved these changes
🚢 🚢 🚢

2023-01-05 16:44 UTC, merged