feat: groups are collapsable in explorer sidebar even when a field is…
lightdash/lightdash pull request #4267
Opened 2023-01-25 16:48 UTC by yasmin-e

Closes: #4210 

### Description

In the Explore sidebar, when you select a field from the toggle list, the toggle list can no longer be collapsed. This is a bit annoying if you have really wide tables with loads of dimensions. 

![image](https://user-images.githubusercontent.com/31848148/213249470-3cbd9510-4a82-4ac4-b701-2a4c5d450387.png)

Maybe we could allow them to be collapsed then add some number indicator on the collapsed list to show the number of fields used from that list?

2023-01-25 18:47 UTC, hamzahc1 commented
Seeing something odd when I try to collapse a group with a selected dimension:

https://user-images.githubusercontent.com/14341285/214655272-cebe5194-bb49-4599-997d-074c7d21ab02.mov

2023-01-25 19:56 UTC, hamzahc1 requested changes
Seeing something odd when I try to collapse a group with a selected dimension. a negative number pops up?:

https://user-images.githubusercontent.com/14341285/214675197-fe5fdcd9-4843-4349-b933-959a5565ebdc.mov

2023-01-26 14:46 UTC, owlas requested changes

2023-01-26 14:46 UTC, owlas commented on packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeGroupNode.tsx
> +    const isDisabled = forceOpen;
This variable isn't needed

2023-01-26 14:46 UTC, owlas commented on packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeGroupNode.tsx
> +    const selectedChildrenCount = intersectionBy(
How was this being calculated before?

2023-01-26 14:55 UTC, yasmin-e commented on packages/frontend/src/components/Explorer/ExploreTree/TableTree/Tree/TreeGroupNode.tsx
> +    const selectedChildrenCount = intersectionBy(
it wasn't

2023-01-27 00:05 UTC, merged