wip: scheduler frequency inputs
lightdash/lightdash pull request #4470
Opened 2023-02-14 17:41 UTC by ZeRego

Closes: #4113 

### Description:

2023-02-15 14:27 UTC, ZeRego commented on packages/frontend/src/components/SchedulerModals/SchedulerModalBase/index.tsx
> +            // TODO: remove forceSuccess
This is to allow reviewing without enabling slack.
I will remove this after approval.

2023-02-16 10:14 UTC, rephus commented
Could we increase the size of this select a bit to show the full string ? 
![image](https://user-images.githubusercontent.com/1983672/219336342-2f153968-52bc-4484-8a1b-e599d9c136ad.png)

2023-02-16 10:24 UTC, rephus commented
is this expression not valid ? :( I guess we'll have to create multiple schedulers to cover cases like this  
![image](https://user-images.githubusercontent.com/1983672/219338547-1e39e8fc-af4c-4801-932c-5a385e9b3c59.png)

2023-02-16 10:28 UTC, rephus commented
Eventually we will have to convert all these UTC inputs into local time (maybe except for custom) , or at least show the time locally (on a label or something). This can be done on a separate PR

2023-02-16 10:31 UTC, rephus commented
Not related with this PR, but should we allow schedulers without targets ? 
[Screencast from 16-02-23 11:30:44.webm](https://user-images.githubusercontent.com/1983672/219340567-5f14a551-6b73-424e-89cd-686b09da597e.webm)

2023-02-16 11:11 UTC, rephus requested changes
Amazing, this was a lot harder than I expected, but you did a great job. It works super well.  I didn't find anything wrong in the code.

Just fix a few changes in the UI and then we can merge it.

2023-02-16 16:13 UTC, ZeRego commented
> This monthly select looks weird ![image](https://user-images.githubusercontent.com/1983672/219336787-94183d93-af9e-4d86-85fe-6e26574f5719.png)

@rephus Can't replicate this :/

2023-02-16 16:16 UTC, ZeRego commented
> Not related with this PR, but should we allow schedulers without targets ?
> [Screencast from 16-02-23 11:30:44.webm](https://user-images.githubusercontent.com/1983672/219340567-5f14a551-6b73-424e-89cd-686b09da597e.webm)

We need to upgrade `react-hook-form` to the latest version to be able to validate arrays. 
```rules: { minLength: 4 }```

2023-02-16 17:01 UTC, ZeRego commented on packages/frontend/src/utils/fieldValidators.ts
> +const cronValueRegex = new RegExp(
Improved validation
![Captura de ecrã 2023-02-16, às 17 00 35](https://user-images.githubusercontent.com/9117144/219435712-ff6c4bc2-349e-4757-8fbc-ca9ec994d483.png)

2023-02-16 17:02 UTC, ZeRego commented on packages/frontend/src/components/SchedulerModals/SchedulerModalBase/SchedulerForm.tsx
> +                                    isAddEmailDisabled
Fixed issue where tooltips don't close when button is disabled

2023-02-17 07:34 UTC, rephus commented
> > This monthly select looks weird ![image](https://user-images.githubusercontent.com/1983672/219336787-94183d93-af9e-4d86-85fe-6e26574f5719.png)
> 
> @rephus Can't replicate this :/

Maybe it is just my browser (firefox on linux) , but we can easily fix this by settiong `width: 150px` on numeric input 

before: 
![image](https://user-images.githubusercontent.com/1983672/219579614-0ad27cfb-dd20-470a-9687-07e5eb5c64ca.png)

after: 

![image](https://user-images.githubusercontent.com/1983672/219579708-fc5bbc64-1682-47d0-a301-af83a6af0115.png)

2023-02-17 07:38 UTC, rephus commented
When I `create a new scheduler` with any frequency, then I go to `edit` it always defaults to `weekly` , this doesn't happen if you update a scheduler 

[Screencast from 17-02-23 08:37:01.webm](https://user-images.githubusercontent.com/1983672/219580596-b673925d-3435-47ce-afc6-cf48af35bc8c.webm)

2023-02-20 07:27 UTC, rephus approved these changes
:man_cook: :ok_hand:

2023-02-20 09:59 UTC, merged