refactor: use tsoa for org router
lightdash/lightdash pull request #4520
Opened 2023-02-20 10:39 UTC by owlas

getting there...

2023-02-20 10:41 UTC, owlas commented on packages/backend/src/controllers/organizationController.ts
> +    async updateOrganizationMember(
moved one line of biz logic from here to the service

2023-02-20 10:41 UTC, owlas commented on packages/backend/src/models/OrganizationModel.ts
> +        data: UpdateOrganization,
narrowed and renamed type

2023-02-20 10:42 UTC, owlas commented on packages/backend/src/services/OrganizationService/OrganizationService.ts
> +        data: UpdateOrganization,
This had the wrong type but wasn't caught without validation on old routes

2023-02-20 10:43 UTC, owlas commented on packages/backend/src/services/UserService.ts
> +        if (user.userUuid === userUuidToDelete) {
biz logic migrated from the old router

2023-02-20 10:43 UTC, owlas commented on packages/common/src/authorization/types.ts
> +interface Organization {
moved this because it was causing confusion with `Organisation` - not exported

2023-02-20 10:43 UTC, owlas commented on packages/common/src/authorization/organizationMemberAbility.test.ts
> +            const org = { organizationUuid: '789' };
type no longer exported

2023-02-20 10:44 UTC, owlas commented on packages/common/src/types/organization.ts
> +export type UpdateOrganization = Partial<
Narrowed this from the previous `UpdateOrganisation`

2023-02-20 10:55 UTC, owlas commented on packages/common/src/index.ts
> +export * from './types/projects';
moved some project types to a separate types file

2023-02-20 10:55 UTC, owlas commented on packages/common/src/index.ts
> +import {
moved more org types to a separate type file

2023-02-21 12:09 UTC, ZeRego commented on packages/backend/src/controllers/organizationController.ts
> +        @Header(LightdashRequestMethodHeader) method: RequestMethod,
Perhaps we should type this as a potential `undefined` and default to `RequestMethod.UNKNOWN` in `projectService.create()`

2023-02-21 12:23 UTC, ZeRego commented
The code looks good but would be nice to see the CLI tests passing since this touches a few of the endpoints that the CLI uses. 
If this was updated in multiple PR's and controllers so be easier to test manually.

2023-02-22 14:18 UTC, ZeRego approved these changes
lgtm 👍 Left suggestions in other comments

2023-02-24 13:59 UTC, rephus requested changes
I've enabled tests, but these ones are failing

![image](https://user-images.githubusercontent.com/1983672/221196826-a58291c8-249c-438f-9001-53e1f6e431be.png)

2023-02-24 16:05 UTC, owlas commented
taking a look!

2023-02-27 15:33 UTC, owlas commented
Closing in favour of #4607 #4611 #4612 #4613 #4614

2023-02-27 15:37 UTC, closed without merging