fix: redirct after space deletion
lightdash/lightdash pull request #4677
Opened 2023-03-03 17:24 UTC by Chrischuck

Closes: #4665 

### Description:

Uploading delete-test.mov…

2023-03-06 07:27 UTC, rephus requested changes

2023-03-06 07:27 UTC, rephus commented on packages/frontend/src/hooks/useSpaces.ts
> +                    pathname: `/projects/${projectUuid}/spaces`,
This mutation could be  used anywhere, so we should not assume we are deleting spaces from /spaces page . If we want to fix  #4665 we simply need to remove this redirection.

2023-03-06 14:11 UTC, Chrischuck commented
@rephus Done!

2023-03-06 15:18 UTC, rephus requested changes

2023-03-08 15:04 UTC, IrakliJani commented
Hey there @Chrischuck! Just wanted to give you a heads up that some of the tickets you picked up are from our backlog that we prioritized to close this week. Do you think you'll be able to wrap them up today? If you need any assistance or don't have enough time, no worries! Just let us know and we'll be happy to take care of it for you 🙌

2023-03-10 15:23 UTC, closed without merging