feat: migrate landing panel to Mantine
lightdash/lightdash pull request #4833
Opened 2023-03-16 14:39 UTC by yasmin-e

Closes: #4810 

### Description:
before
<img width="994" alt="Screenshot 2023-03-16 at 15 39 11" src="https://user-images.githubusercontent.com/67699259/225651905-a30cbf6f-5014-4be7-b624-f016647b0269.png">

after
<img width="957" alt="Screenshot 2023-03-17 at 12 37 27" src="https://user-images.githubusercontent.com/67699259/225894223-ef77556d-6ac5-4aa3-8fa9-874034b29089.png">

2023-03-16 18:01 UTC, hamzahc1 commented
@yasmin-e - the Run a Query icon is different to previously, is this intentional?

2023-03-16 19:01 UTC, yasmin-e commented
> @yasmin-e - the Run a Query icon is different to previously, is this intentional?

yes! assume that all icon changes on mantine migrations are prev. approved by @PriPatel  :)

2023-03-16 19:12 UTC, PriPatel commented
Yes! 
For a few reasons

1. The old icon doesnt make much sense and we couldn't find a suitable match
2. The table icon is more consistent with what you see in the navbar
<img width="376" alt="Screenshot 2023-03-16 at 19 15 04" src="https://user-images.githubusercontent.com/12776522/225728484-f78bfe23-fc6a-4de4-af00-2107c881809b.png">

The other option was no icon - Im also happy with that!

2023-03-17 08:48 UTC, IrakliJani requested changes
minor comments

2023-03-17 08:48 UTC, IrakliJani commented on packages/frontend/src/components/common/PrimaryLinkButton.tsx
ignoring

2023-03-17 08:48 UTC, IrakliJani commented on packages/frontend/src/components/Home/OnboardingPanel/index.tsx
ignoring

2023-03-17 08:48 UTC, IrakliJani commented on packages/frontend/src/components/Home/OnboardingPanel/OnboardingSteps.styles.tsx
ignoring

2023-03-17 08:48 UTC, IrakliJani commented on packages/frontend/src/components/Home/LandingPanel/LandingPanel.styles.tsx
>  `;
are we using this someplace else? if yes, can we get rid of it from this file and move where it's necessary?

2023-03-17 08:49 UTC, IrakliJani commented
re-running tests ✅

2023-03-17 13:45 UTC, IrakliJani approved these changes

2023-03-17 15:10 UTC, merged

2023-03-17 15:18 UTC, owlas commented
:tada: This PR is included in version 0.468.0 :tada:

The release is available on:
- `0.468.0`
- [GitHub release](https://github.com/lightdash/lightdash/releases/tag/0.468.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: