feat: break out s3 image expiration time to env variable
lightdash/lightdash pull request #4955
Opened 2023-03-29 13:27 UTC by gictor

### Description:
Break out expiration time to an environment variable

2023-03-29 13:57 UTC, rephus approved these changes
Looks good to me, thanks for your contribution !

2023-03-29 13:57 UTC, rephus commented on docs/docs/guides/enable-cloud-storage.mdx
> +`S3_REGION` for google is `auto`
Cool

2023-03-29 13:57 UTC, rephus commented on packages/backend/src/config/parseConfig.ts
> +            expirationTime: process.env.S3_EXPIRATION_TIME,
nice !

2023-03-29 14:07 UTC, rephus requested changes
One of the tests are failing because it is not formatted properly... did you run our commit hooks ? 

If you can't do it, I'll have to create a separate branch to merge this

![image](https://user-images.githubusercontent.com/1983672/228564591-5bb7243a-ed10-48bb-8c3e-5989ac58eee8.png)

2023-03-29 14:28 UTC, rephus commented
@all-contributors add @gictor  for code

2023-03-29 19:24 UTC, gictor commented
> One of the tests are failing because it is not formatted properly... did you run our commit hooks ?
> 
> If you can't do it, I'll have to create a separate branch to merge this
> 
> ![image](https://user-images.githubusercontent.com/1983672/228564591-5bb7243a-ed10-48bb-8c3e-5989ac58eee8.png)

You are correct! I think I got it right now :)

2023-03-30 07:31 UTC, rephus approved these changes

2023-03-30 07:31 UTC, merged