fix: adding open dashboard button to update chart success toast
lightdash/lightdash pull request #5095
Opened 2023-04-14 15:26 UTC by yasmin-e

Closes: #4056 

### Description:
before

https://user-images.githubusercontent.com/67699259/232087477-681db02a-0c65-464a-a231-74c5cb183d36.mov

after

https://user-images.githubusercontent.com/67699259/232087500-a3be4ea2-3cf9-4814-a375-11b9d98d08fb.mov

2023-04-14 17:36 UTC, IrakliJani commented on packages/frontend/src/hooks/useSavedQuery.ts
>  export const useUpdateMutation = (savedQueryUuid?: string) => {
this is being used in one more place. I would extract both as I've seen using code like this produce bugs previously

```
    const { projectUuid } = useParams<{ projectUuid: string }>();
    const dashboardUuid = useSearchParams('fromDashboard');
```

out of this hook and input as params

2023-04-17 06:38 UTC, rephus requested changes

2023-04-17 06:38 UTC, rephus commented on packages/frontend/src/components/common/modal/ChartUpdateModal.tsx
> +        dashboardUuid!,
we cannot enforce a dashboardUuid here, this works if you are updating a chart from a dashboard, but you can also update charts without a dashboard . This field needs to be optional (string | undefined) and only redirect if provided


[Screencast from 31-03-23 16:43:39.webm](https://user-images.githubusercontent.com/1983672/232403955-4e1a0cb0-5512-4796-af25-778de690357b.webm)

2023-04-17 15:04 UTC, rephus approved these changes

2023-04-17 15:06 UTC, merged