feat: mantine page wrappers + sidebar
lightdash/lightdash pull request #5301
Opened 2023-05-02 09:31 UTC by IrakliJani

Closes: https://github.com/lightdash/lightdash/issues/4896
Closes: https://github.com/lightdash/lightdash/issues/5332
Closes: https://github.com/lightdash/lightdash/issues/5351

### Description:

- [x] create new page component which abstracts all other page wrappers with simple props
migrates
- [x] migrate old sidebar and use it everywhere

new page styling options
```
    withFixedContent?: boolean;
    withFooter?: boolean;
    withFullHeight?: boolean;
    withHeader?: boolean;
    withNavbar?: boolean;
    withSidebar?: boolean;
    withSidebarFooter?: boolean;
    withPaddedContent?: boolean;
    withCenteredContent?: boolean;
```

2023-05-02 16:57 UTC, joaoviana commented on packages/frontend/src/pages/CreateProjectSettings.tsx
> +
do you like to have this new line separation between modules and non-module imports?

2023-05-02 17:04 UTC, joaoviana requested changes
wow! a few qs and requests!

2023-05-02 17:04 UTC, joaoviana commented on packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
> +// padding-left: ${SIDEBAR_WIDTH}px;
perhaps can be removed?

2023-05-02 17:04 UTC, joaoviana commented on packages/frontend/src/components/common/Page/Page.tsx
> +const usePageStyles = createStyles<string, StyleProps>((theme, params) => {
👏

2023-05-02 17:28 UTC, IrakliJani commented on packages/frontend/src/pages/UserActivity.tsx
> +        <Page title={`User activity for ${project?.name}`}>
no more, Page component takes care of it

2023-05-02 17:28 UTC, IrakliJani commented on packages/frontend/src/pages/SqlRunner.tsx
> +            title="SQL Runner"
Inside page

```
            {title ? (
                <Helmet>
                    <title>{title} - Lightdash</title>
                </Helmet>
            ) : null}
```

2023-05-02 17:28 UTC, IrakliJani commented on packages/frontend/src/pages/SavedExplorer.tsx
> +                sidebarOpened={isEditMode}
updated!

2023-05-02 17:29 UTC, IrakliJani commented on packages/frontend/src/pages/SavedDashboards.tsx
> +        <Page title="Dashboards" withFixedContent>
all inner pages are width 100%

`withFixedContent` applies this styles so it's covered

```
  marginLeft: 'auto',
  marginRight: 'auto',
  width: 900,
```

2023-05-02 17:30 UTC, IrakliJani commented on packages/frontend/src/mantineTheme.ts
> +            backgroundColor: theme.colors.gray[0],
ya, we were applying bg color only on some routes and not on body or html

2023-05-02 17:30 UTC, IrakliJani commented on packages/frontend/src/components/ProjectConnection/ProjectConnection.styles.tsx
> +// padding-left: ${SIDEBAR_WIDTH}px;
all gone!

2023-05-03 07:28 UTC, joaoviana approved these changes
🚢 it!

2023-05-03 17:33 UTC, joaoviana approved these changes

2023-05-04 07:06 UTC, merged