fix: editors should be able to pin
lightdash/lightdash pull request #5417
Opened 2023-05-09 14:09 UTC by yasmin-e

Closes: #5375 

### Description:
```
- [ ] Making re-order feature hidden for users without permission to manage Pinned Items
- [ ] New PinnedItems ability object
- [ ] Admins, editors, and developers can manage pinned items: pin/unpin and re-order
- [ ] All other roles can only view
```

2023-05-09 15:57 UTC, TuringLovesDeathMetal approved these changes
Nice! Looks good to me 🚀

2023-05-10 09:45 UTC, joaoviana requested changes
only one small thing, then good to go!

2023-05-10 09:45 UTC, joaoviana commented on packages/frontend/src/components/PinnedItemsPanel/index.tsx
> +    console.log({ userCanManagePinnedItems, user });
could you remove this pls?

2023-05-10 09:54 UTC, ZeRego commented on packages/frontend/src/components/common/ResourceView/ResourceActionMenu.tsx
> +                    subject('PinnedItems', { organizationUuid, projectUuid }),
We need the same fix on packages/frontend/src/components/Explorer/SpaceBrowser/SpaceBrowserMenu.tsx

2023-05-10 13:40 UTC, ZeRego approved these changes

2023-05-10 13:51 UTC, joaoviana approved these changes

2023-05-10 14:04 UTC, merged