feat: enable new pivot table
lightdash/lightdash pull request #5434
Opened 2023-05-10 17:57 UTC by IrakliJani

Closes: https://github.com/lightdash/lightdash/issues/4932

### Description:

## TODO
- [x] column totals (case when you have not enabled metrics as rows)
- [x] replace old pivot table with the new one
- [x] remove old pivot table related code
- [x] fix pivots with only indexes or only headers
- [x] fix existing specs
- [x] add specs for "everything on columns"

https://github.com/lightdash/lightdash/assets/962095/aebe976a-ffc6-4a9d-9a4d-81d479d362a8

### header only dimensions (**without** metrics as rows):
![image](https://github.com/lightdash/lightdash/assets/962095/491695f0-0059-4b07-bbcf-5abe7dd1da04)

### index only dimensions (**with** metrics as rows)
![image](https://github.com/lightdash/lightdash/assets/962095/22bb9776-6ffe-4832-a324-dd44ea7757f8)

### error state
<img width="445" alt="CleanShot 2023-05-11 at 23 02 26@2x" src="https://github.com/lightdash/lightdash/assets/962095/b5e8dc46-8c5b-4ee5-9f7b-a6b7298238a4">

2023-05-15 14:32 UTC, TuringLovesDeathMetal requested changes
Looking way better than the old pivot tables 😍 

Two changes:

1. Don't remove column totals when you only have one row. Agreed that it’s useless, but I’d actually keep this in there. The reason being: If I clicked on it and only had one row, I’d be confused why it wasn’t appearing. I think we should keep it in and if someone doesn’t like the look of it, then they can just remove the totals option from their config.
2. Should we sum 0s in totals? Yes, let’s add this - it looks weird that they’re not summed.

2023-05-15 16:29 UTC, ZeRego commented on packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
> +            };
Not sure why we return empty rows in this case.

2023-05-15 16:29 UTC, ZeRego commented on packages/frontend/src/hooks/tableVisualization/useTableConfig.ts
> +            console.error(e);
Reminder: remove console.log

2023-05-15 16:30 UTC, ZeRego commented on packages/frontend/src/components/common/PivotTable/index.tsx
> +                                        {value.formatted}
The total calculation doesn't have the same rules as before. We only show totals if:
- metric type is: number, count, count distinct, sum
- formatting is not 'percent'

This pivot table shows totals for any numeric column.

2023-05-16 09:47 UTC, ZeRego commented
Fixes:
- only show totals for correct columns/rows
- show total `0` 
- show the total when there is only 1 row ( this was already working )

![Captura de ecrã 2023-05-16, às 10 43 44](https://github.com/lightdash/lightdash/assets/9117144/8db8edb4-fcae-4711-ba1d-626e83744a3e)
![Captura de ecrã 2023-05-16, às 10 41 05](https://github.com/lightdash/lightdash/assets/9117144/c7ec0ec8-70e8-4ee1-87f6-b49a7341774e)
![Captura de ecrã 2023-05-16, às 10 40 27](https://github.com/lightdash/lightdash/assets/9117144/c57f3a7b-e4fb-4962-9b79-db67056f5116)

2023-05-16 10:37 UTC, TuringLovesDeathMetal approved these changes
looks good!

2023-05-16 10:48 UTC, merged