docs: add cli validate
lightdash/lightdash pull request #5654
Opened 2023-05-29 08:03 UTC by rephus

Closes: #5327

### Description:

2023-05-29 08:14 UTC, rephus commented
I'm not sure how to add this doc to the sidebar...

2023-05-29 13:14 UTC, IrakliJani approved these changes

2023-05-30 09:14 UTC, TuringLovesDeathMetal commented on docs/docs/guides/cli/how-to-use-lightdash-validate.mdx
> +You can trigger a validation on a project from the CLI, this will allow you to block a release (using Github actions)
```suggestion
You can check to see if your changes break any of the content in your project using `lightdash validate`. This command will run the validator which will return a list of content in your project that is broken and details about the errors. 

You can trigger a validation on a project using the Lightdash CLI so you can check locally if your changes will break anything. You can also add `lightdash validate` to your [GitHub Actions](/guides/cli/how-to-use-lightdash-validate.mdx/configure-github-actions) so changes can't be merged unless they pass the validation. 
```

2023-05-30 09:16 UTC, TuringLovesDeathMetal requested changes
This is really great @rephus!

Just one small recommendation for some copy change 👀 

Also, for the "GitHub actions" bit - do you have to do anything beyond adding that bit of text? Or would you need to do something else to block the PR (like add a command or something that says `if failed, then`)

2023-05-30 09:19 UTC, TuringLovesDeathMetal commented on docs/docs/guides/cli/how-to-use-lightdash-validate.mdx
> +## Configure Github actions
Can we add a bit here that references the docs on how to set up GitHub actions? I think there are docs where we talk about the templates? 🤔 

Or maybe we actually need to create a separate reference doc just for GitHub actions + all the actions you can do (I can create a separate issue for that). 
 

In the meantime though, maybe we can add something like this at the bottom of the section?:

```
To learn more about setting up GitHub actions for Lightdash, check out the docs here..
```

2023-05-30 11:24 UTC, TuringLovesDeathMetal approved these changes
Nice! looks great 😚 👌

2023-05-30 11:28 UTC, merged