feat: Add APIs to add and revoke space-level access
lightdash/lightdash pull request #5849
Opened 2023-06-12 07:49 UTC by yu-iskw

Enhances: https://github.com/lightdash/lightdash/issues/5666

### Description:
Added methods.

- `POST /projects/{projectUuid}/spaces/{spaceUuid}/share`
- `DELETE /projects/{projectUuid}/spaces/{spacesUuid}/share/{userUuid}`

### What we have to do in the pull request
- [x] Update `reouts.ts` and `swagger.json`

2023-06-12 14:26 UTC, rephus requested changes
Thanks for your contribution. 

The new endpoints look good, but we should replace the existing endpoint from `projectRouter`and use the same endpoints 

- add space share: https://github.com/lightdash/lightdash/blob/main/packages/backend/src/routers/projectRouter.ts#L403
- remove space share: https://github.com/lightdash/lightdash/blob/main/packages/backend/src/routers/projectRouter.ts#L420

2023-06-12 14:26 UTC, rephus commented on packages/backend/src/controllers/spaceController.ts
> +    @Tags('Roles & Permissions')
Nice tag

2023-06-12 21:48 UTC, yu-iskw reviewed
@rephus Thank you for the comments. I have changed the paths in the controller so that those follows the router.

2023-06-12 21:48 UTC, yu-iskw commented on packages/backend/src/controllers/spaceController.ts
> +    @Post('{spaceUuid}/share')
I have changed the path.

2023-06-12 21:48 UTC, yu-iskw commented on packages/common/src/types/space.ts
> +export type AddSpaceShare = Pick<SpaceShare, 'userUuid'>;
I added a new type for the body of `addSpaceShare`.

2023-06-13 06:41 UTC, rephus commented
Great @yu-iskw we also need to remove the endpoints in the old "router" we don't want to have duplicated items. Once we do that, we can test this new endpoints on our preview environment to see if the behaviour is the same

2023-06-13 15:15 UTC, merged

2023-06-14 01:49 UTC, yu-iskw commented
@rephus Thank you for merging! I look forward to releasing the APIs to Lightdash Cloud.