fix: check if fieldId exists in metric filters underlying data modal
lightdash/lightdash pull request #6023
Opened 2023-06-22 11:45 UTC by joaoviana

Closes: #6022

### Description:

Check first it `fieldId` exists, and if so, get the correct value. If not, convert `fieldRef` to a field ID.

2023-06-22 12:35 UTC, owlas requested changes
Isn't this a change we should make on the backend when loading saved charts with old style custom metrics, and fix it further upstream (in case there are other FE dependencies that haven't been updated)

2023-06-22 12:38 UTC, joaoviana commented
> Isn't this a change we should make on the backend when loading saved charts with old style custom metrics, and fix it further upstream (in case there are other FE dependencies that haven't been updated)

but these are metrics with filters applied 🤔  but agree with changing on the BE, looking into it!

2023-06-23 11:29 UTC, joaoviana commented on packages/backend/src/models/ProjectModel/ProjectModel.test.ts
> +                mockExploresFromCache[0],
can remove the other explores and just keep the first one in `ProjectModel.mock`. What do we think?

2023-06-23 13:05 UTC, ZeRego approved these changes

2023-06-23 14:42 UTC, merged