feat: support `--vers` option in the CLI
lightdash/lightdash pull request #6099
Opened 2023-06-30 04:58 UTC by yu-iskw

Closes: https://github.com/lightdash/lightdash/issues/6098

### Description:
The `--vars` option is supported in some sub commands of Lightdash CLI. However, `CompileHandlerOptions` doesn't have the `vars` field.

2023-07-03 12:26 UTC, rephus commented
Looks good, testing on render

2023-07-03 13:02 UTC, rephus commented
There is an error on the e2e test : 

![image](https://github.com/lightdash/lightdash/assets/1983672/5e8b2791-37b3-4978-990e-39426cab3056)

2023-07-03 13:05 UTC, rephus requested changes
See error

2023-07-03 21:09 UTC, yu-iskw commented
@rephus Sure. I will look into it.

2023-07-03 21:35 UTC, yu-iskw commented on packages/cli/src/handlers/dbt/run.ts
> +type DbtRunHandlerOptions = DbtCompileOptions & {
Some type aliases like `GenerateHandlerOptions` take advantage of `CompileHandlerOptions`. But, I feel `DbtCompileOptions` would look more natural in this case, as `DbtRunHandlerOptions` isn't exposed as command line options.

2023-07-04 08:06 UTC, rephus approved these changes

2023-07-04 09:21 UTC, merged