Chore/avoid cli seed error
lightdash/lightdash pull request #6137
Opened 2023-07-04 11:07 UTC by ZeRego

Closes: #5943 

### Description:

Changes:
- combine both github actions into 1
- run in parallel
- use different schemas for each job

2023-07-04 15:51 UTC, ZeRego commented on .github/workflows/e2e-tests.yml
> +    name: App (${{ matrix.containers }}/${{ strategy.job-total }})
Fix job names since `strategy.job-index` starts at 0

2023-07-05 06:44 UTC, rephus requested changes

2023-07-05 06:44 UTC, rephus commented on .github/workflows/cli-tests.yml
> +          SEED_SCHEMA: jaffle-${{strategy.job-index}}
I think this should be CYPRESS_SEED_SCHEMA if you want to get this using `Cypress.env('SEED_SCHEMA')`

2023-07-05 06:44 UTC, rephus commented on .github/workflows/cli-tests.yml
> +        dbt: ['1.3', '1.4', '1.5' ]
:kissing: :ok_hand:

2023-07-05 15:56 UTC, ZeRego commented on .github/workflows/e2e-tests.yml
> +        timezone: ['America/New_York', 'Europe/Madrid', 'Asia/Tokyo' ]
removed UTC since this is already covered in the App tests

2023-07-05 15:56 UTC, ZeRego commented on .github/workflows/e2e-tests.yml
> +          name: cypress-screenshots-and-videos-${{ strategy.job-index }}
fix typo

2023-07-05 15:57 UTC, ZeRego commented on .github/workflows/e2e-tests.yml
> +        containers: [ 1, 2, 3 ]
reduced amount of jobs since the PR env was struggling. we can try to increase it again later.

2023-07-06 06:45 UTC, rephus approved these changes

2023-07-06 08:26 UTC, merged