fix:  title change tile
lightdash/lightdash pull request #6291
Opened 2023-07-12 14:37 UTC by rephus

Closes:  #6285

### Description:

[Screencast from 12-07-23 16:35:24.webm](https://github.com/lightdash/lightdash/assets/1983672/7e124026-3e5b-49bf-b328-d4db2ffc01fe)

2023-07-12 14:53 UTC, ZeRego requested changes

2023-07-12 14:53 UTC, ZeRego commented on packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
> +                                    title: undefined,
`TileUpdateModal` is used for all tile types. This would remove the title from any change in the loom/markdown tile

2023-07-12 14:54 UTC, ZeRego commented on packages/frontend/src/components/DashboardTiles/TileBase/index.tsx
> +                                    title: undefined,
This fix might be easier after the changes from this PR https://github.com/lightdash/lightdash/pull/6281

2023-07-13 07:24 UTC, yasmin-e reviewed
Looks great 👍🏼 
I just noticed something and I'm not sure this is the intended behaviour 🤔 (it's not crucial though)
Here are the steps:
1. Replace chart 
2. Edit title
3. The title placeholder is the original chart's title (not the replaced one)
<img width="836" alt="Screenshot 2023-07-13 at 9 22 55" src="https://github.com/lightdash/lightdash/assets/67699259/321f66ad-75ba-4553-b731-f2a1dcbec909">

2023-07-13 08:21 UTC, rephus commented
Mmm, I can't replicate this... 

[Screencast from 13-07-23 10:20:30.webm](https://github.com/lightdash/lightdash/assets/1983672/36b1c238-427d-42b5-9092-819e694a2907)

2023-07-13 10:42 UTC, ZeRego approved these changes

2023-07-13 10:43 UTC, merged