feat: copy chart in dashboard preview
lightdash/lightdash pull request #6466
Opened 2023-07-24 15:13 UTC by rephus

Closes: [#6393](https://github.com/lightdash/lightdash/issues/6393)

### Description:

![Screenshot from 2023-07-24 17-10-25](https://github.com/lightdash/lightdash/assets/1983672/1dc5fdeb-b95a-402f-8d9a-e6fac5690285)
![Screenshot from 2023-07-24 17-12-26](https://github.com/lightdash/lightdash/assets/1983672/b2b42f50-4dc8-42d8-835c-c6c97e0fdff1)
![Screenshot from 2023-07-24 17-11-05](https://github.com/lightdash/lightdash/assets/1983672/1f10bc94-56b5-4b70-9dfa-e5c9bc472abe)

2023-07-24 15:14 UTC, rephus commented on packages/backend/src/database/entities/savedCharts.ts
> +            | 'dashboard_uuid'
needed for update

2023-07-24 16:07 UTC, ZeRego requested changes

2023-07-25 06:59 UTC, rephus commented on packages/backend/src/models/ProjectModel/ProjectModel.ts
> +            await chartsInDashboards.map(async (chart) => {
:facepalm: good catch

2023-07-25 08:32 UTC, ZeRego approved these changes

2023-07-25 08:46 UTC, merged