wip: nested filters
lightdash/lightdash pull request #6530
Opened 2023-07-28 11:27 UTC by ZeRego

Closes: #3700 

### Description:

2023-07-31 10:37 UTC, owlas reviewed
Is this an existing bug? It doesn't look like we're nesting the filters in the metrics section: 

<img width="553" alt="CleanShot 2023-07-31 at 11 36 45@2x" src="https://github.com/lightdash/lightdash/assets/11660098/5c89d7a3-d43a-4ffc-b623-76d482cdd4e7">

<img width="1468" alt="CleanShot 2023-07-31 at 11 37 13@2x" src="https://github.com/lightdash/lightdash/assets/11660098/1c512147-8c0e-4a55-b240-63d34cc3a597">

2023-07-31 10:42 UTC, owlas commented
✅ works well even when nesting goes beyond 2 levels deep:

<img width="1492" alt="CleanShot 2023-07-31 at 11 42 02@2x" src="https://github.com/lightdash/lightdash/assets/11660098/363dbed7-1b66-4cac-8746-975b1f2c100e">

2023-07-31 14:16 UTC, ZeRego commented
@owlas Added support for nested metric filters. ( unit test included )

![Screenshot 2023-07-31 at 15 14 46](https://github.com/lightdash/lightdash/assets/9117144/e9330ecc-c923-4e67-a757-0e3acf884b3a)

2023-08-01 11:14 UTC, owlas requested changes
If you "explore from here" with no dashboard filters, it renders a little off. Functionally still works.

Tested everything else and worked perfectly, so last change! 

<img width="1473" alt="CleanShot 2023-08-01 at 12 13 25@2x" src="https://github.com/lightdash/lightdash/assets/11660098/13ed2823-5745-46a2-a96f-8d2ae703e4a0">

2023-08-01 12:40 UTC, ZeRego commented
@owlas fixed. We now only show the dimension/metric section if there are rules in it.

Explore from here a chart in a dashboard that has dimension filters
![Screenshot 2023-08-01 at 13 38 09](https://github.com/lightdash/lightdash/assets/9117144/00e89589-5168-42d0-ac13-a5e0c045c3a3)

Explore from here a chart in a dashboard that has metrics filters
![Screenshot 2023-08-01 at 13 38 41](https://github.com/lightdash/lightdash/assets/9117144/d3ad6ab7-70b4-4160-b2b1-bbb67582b790)

2023-08-01 13:08 UTC, merged