feat: add private channels input
lightdash/lightdash pull request #6625
Opened 2023-08-04 15:20 UTC by rephus

Closes: [#6284](https://github.com/lightdash/lightdash/issues/6284)

### Description:

Only UI changes, 

we allow the user to type the name of the private channel directly.

[Screencast from 04-08-23 17:20:07.webm](https://github.com/lightdash/lightdash/assets/1983672/e39ee88d-7717-443c-9efc-a0f651a4ad42)

![Screenshot from 2023-08-04 17-15-39](https://github.com/lightdash/lightdash/assets/1983672/88776b1d-22e6-4a94-b994-9116801d5d03)

2023-08-04 16:50 UTC, ZeRego approved these changes

2023-08-04 19:01 UTC, hamzahc1 requested changes
Mentioned in the original issue, can we add an information tooltip to the right of the input box that says "If delivering to a private Slack channel, please type the name of the channel in the input box exactly as it appears in Slack. Also ensure you invite the Lightdash Slackbot into that channel."

2023-08-07 07:07 UTC, rephus commented
Updated

![image](https://github.com/lightdash/lightdash/assets/1983672/ce0bd4d6-e053-42d3-9c0b-71620e938b10)

2023-08-07 08:43 UTC, hamzahc1 approved these changes

2023-08-07 09:54 UTC, merged