feat: Migrate project settings forms to use Mantine
lightdash/lightdash pull request #6988
Opened 2023-09-03 20:11 UTC by jayanand05

### Description:
This PR closes one task from Warehouse connection (i.e PostgreSQL) defined in the issue #5402

https://github.com/lightdash/lightdash/assets/113882904/35cc890c-8001-47e7-8394-6e986c8bf494

2023-09-08 13:49 UTC, ZeRego requested changes

2023-09-08 13:49 UTC, ZeRego commented on packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
> +                    required
User and password are not required when editing.
```required: requireSecrets ? 'Required field' : undefined,```

2023-09-08 13:49 UTC, ZeRego commented on packages/frontend/src/components/ReactHookForm/BooleanSwitch.tsx
> +                onLabel="Yes"
I think we need to increase the Switch size as I can't read the labels.
Now:
![Screenshot 2023-09-08 at 14 10 30](https://github.com/lightdash/lightdash/assets/9117144/9a31c9eb-6a58-4fbb-922b-53e2730d010a)
Before
![Screenshot 2023-09-08 at 14 12 27](https://github.com/lightdash/lightdash/assets/9117144/2afd2a4e-aadb-4ad3-a743-db65bddb86b7)

2023-09-08 13:49 UTC, ZeRego commented on packages/frontend/src/components/ProjectConnection/WarehouseForms/PostgresForm.tsx
> +                <Accordion
I think we should keep using a simple button as we don't take advantage of the accordion functionality. A button with a variant "subtle" and a left icon would simplify the code.

2023-09-08 13:49 UTC, ZeRego commented on packages/frontend/src/components/ProjectConnection/WarehouseSettingsForm.tsx
> +        defaultValue: WarehouseTypes.POSTGRES,
We should keep Bigquery as the default since it's the majority of the users use it.

2023-09-08 13:49 UTC, ZeRego commented on packages/frontend/src/components/ProjectConnection/WarehouseForms/Inputs/StartOfWeekSelect.tsx
> +const defaultOption = { value: ' ', label: 'Auto' };
An empty string will cause issues later on once we enforce API validation.

Let's use `clearable` property instead 👍 
```
                <Select
                    clearable
                    placeholder="Auto"
                    label="Start of week"
                    description="Will be taken into account when using 'WEEK' time interval"
                    data={daysOfWeekOptions}
                    value={field.value}
                    onChange={field.onChange}
                    disabled={disabled}
                    dropdownPosition="top"
                />
```

2023-09-08 15:51 UTC, jayanand05 commented
Hi @ZeRego, i made the necessary changes request you to look at once.

2023-09-08 17:41 UTC, ZeRego requested changes

2023-09-08 17:41 UTC, ZeRego commented on packages/frontend/src/components/ProjectConnection/WarehouseForms/Inputs/StartOfWeekSelect.tsx
> +const defaultOption = { value: ' ', label: 'Auto' };
We can remove `const defaultOption = { value: ' ', label: 'Auto' };` now.

2023-09-08 17:41 UTC, ZeRego commented on examples/full-jaffle-shop-demo/dbt
I think this is rolling back the submodule. Perhaps is better to rebase this branch or rollback this change.

2023-09-08 17:41 UTC, ZeRego commented on packages/frontend/src/components/ProjectConnection/WarehouseSettingsForm.tsx
> +        defaultValue: WarehouseTypes.POSTGRES,
I think you forgot to update this value.

2023-09-18 20:14 UTC, ZeRego approved these changes
Thanks for contributing @jayanand05 🙌 Just had to make some small adjustments.

2023-09-18 20:14 UTC, merged