feat: scheduled deliveries message body
lightdash/lightdash pull request #7189
Opened 2023-09-22 15:30 UTC by IrakliJani

Closes: https://github.com/lightdash/lightdash/issues/6858

### Description:

- [x] In the setup for my scheduled delivery, there is an `advanced options` collapse at the bottom that opens another section
- [x] If I open the toggle, I'm shown the option to `add message body` with a text box that takes markdown. (will markdown work in emails?)
- [x] This message is optional (i.e. it can be left blank).
- [x] If I add a message, then the message appears before any images or files in my email or in Slack. 
- [x] This message goes above the title + description that's currently included as text.

---

- [x] backend
- [x] frontend
- [x] slack blocks
- [ ] email templates

2023-09-26 14:13 UTC, IrakliJani commented
dashboard csvs (no message/no limits):
<img width="955" alt="CleanShot 2023-09-26 at 17 59 55@2x" src="https://github.com/lightdash/lightdash/assets/962095/d604d80a-8455-4b96-b9de-643ef8898426">

---

dashboard csvs (with message/with limits):
<img width="822" alt="CleanShot 2023-09-26 at 17 55 59@2x" src="https://github.com/lightdash/lightdash/assets/962095/2d140bce-fd4b-4d6d-952a-feb2367dd444">

---

chart csv (no message/no limits)
<img width="885" alt="CleanShot 2023-09-26 at 18 00 49@2x" src="https://github.com/lightdash/lightdash/assets/962095/891a98a1-0073-4925-b08c-5b6f90b55f7a">

---

chart csv (with message/with limits)
<img width="859" alt="CleanShot 2023-09-26 at 18 02 09@2x" src="https://github.com/lightdash/lightdash/assets/962095/d1677ce6-48cc-4728-b530-81c7232748f0">

---

chart image (with message)
<img width="751" alt="CleanShot 2023-09-26 at 18 07 54@2x" src="https://github.com/lightdash/lightdash/assets/962095/3620829c-a6f5-49ce-bc12-8e20a2a82b2c">

2023-09-26 16:57 UTC, ZeRego commented on packages/backend/src/scheduler/SchedulerTask.ts
> +            // pdfFile, // TODO: add pdf to slack
forgotten todo ?

2023-09-27 03:51 UTC, IrakliJani commented on packages/backend/src/scheduler/SchedulerTask.ts
> +            // pdfFile, // TODO: add pdf to slack
@ZeRego it was there before

2023-09-27 07:39 UTC, ZeRego approved these changes

2023-09-27 07:42 UTC, ZeRego requested changes
- all Markdown blocks are dark mode now
<img width="932" alt="Screenshot 2023-09-27 at 08 42 17" src="https://github.com/lightdash/lightdash/assets/9117144/e2fe39cc-e39d-4b44-bea1-104f112e6020">

- different UI (link vs button) to view dashboard in app
<img width="837" alt="Screenshot 2023-09-27 at 08 44 24" src="https://github.com/lightdash/lightdash/assets/9117144/832ffece-6e3b-4085-8adc-82f0924bd91d">
<img width="842" alt="Screenshot 2023-09-27 at 08 43 46" src="https://github.com/lightdash/lightdash/assets/9117144/25584d78-c1b6-4b26-a49b-00b78f6ced08">


- ~iirc, emails that were sent with 'send now' had a no scheduled delivery message at the bottom of the email~
  - ignore this, this was only changed for slack messages

2023-09-27 08:36 UTC, IrakliJani commented
@ZeRego just fixed markdown dark mode
about point 2, I asked @PriPatel and it seems to be intentional.

> I think that was intended. Its not a new change. So when you're viewing CSVS, the primary CTA is to download. I dont want people to immediately click on the pick purple CTA. we can change it if anyone feels strongly! But its not a new change, basically.

2023-09-27 09:10 UTC, ZeRego approved these changes

2023-09-27 09:41 UTC, merged