fix: migrate UI project access from blueprint to mantine
lightdash/lightdash pull request #7342
Opened 2023-10-05 10:32 UTC by hrutik7

Closes: #5405 

### Description:

2023-10-10 09:22 UTC, IrakliJani commented
hi @hrutik7 is this PR ready to be reviewed?

2023-10-11 23:54 UTC, hrutik7 commented
hey @IrakliJani not yet . there is something that need to be checked
I'll do it today

2023-10-12 06:51 UTC, IrakliJani commented
cool, looking forward to it @hrutik7

2023-10-18 08:29 UTC, joaoviana requested changes
Thanks for your contribution @hrutik7 ! 
I've requested some changes, please let me know if something's unclear 👍

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/styles/blueprint-core.css
> -}
could we revert this change please? I'm unsure if we're using Blueprint `select`s in other places, so it's less risky to keep until we fully migrate 👍

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
> +                        }}
same here (regarding custom styling). We should try to keep this as _untouched_ as possible, so for example:
* if you want it with less padding, perhaps use `compact`? 
* no custom fonts, background color, margins
* also, try to use the Mantine props for box-model-related styles: `m`/`mx`/`h`/`w`, etc

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccessCreation/index.tsx
> +            }}
Not sure if this is needed 🤔 what would just `Box` look like?

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
> +                                style={{ marginRight: '10', color: '#935610' }}
you can pass `color` prop to this icon 👍

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccess.styles.ts
> +    display: flex;
I would avoid improving/keeping Styled components here, could we do the same with moving these styles + components from `ProjectAccess.styles.ts` to `ProjectAccess.tsx` without using Styled components? Apologies if this is not clear

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
> +                                }}
What about using Mantine's `Select` instead? would be cool 😎

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
> +                                color="dark"
not sure if we need this?

2023-10-18 08:29 UTC, joaoviana commented on packages/frontend/src/components/ProjectAccess/ProjectAccess.tsx
> +    if (isProjectAccessLoading || isProjectAccessLoading) {
this removes the ability to check if `isOrganizationUsersLoading` is true. Can we bring it back?

2023-10-18 08:32 UTC, joaoviana commented
I've also updated the PR description to replace `Closes` with `Relates to` as there's a bit more to do on this ticket 👍

2023-10-23 08:00 UTC, joaoviana commented
I'm closing the PR due to inactivity @hrutik7 , please feel free to open again if you wish to continue contributing 🙌  thanks!

2023-10-23 08:00 UTC, closed without merging