feat: update copy in toast messages
lightdash/lightdash pull request #787
Opened 2021-11-09 16:58 UTC by owlas

2021-11-09 17:02 UTC, TuringLovesDeathMetal approved these changes
Looks good! messages are definitely more clear with the action there first :)

2021-11-09 17:03 UTC, ZeRego requested changes

2021-11-09 17:03 UTC, ZeRego commented on packages/frontend/src/hooks/useSavedQuery.ts
> +                title: `Success! Chart was saved.`,
```suggestion
                title: `Success! Chart was deleted.`,
```

2021-11-09 17:25 UTC, hamzahc1 approved these changes

2021-11-10 14:50 UTC, owlas commented
rebased - waiting for e2e tests

2021-11-10 15:55 UTC, merged