feat: viewer can download csv
lightdash/lightdash pull request #8392
Opened 2023-12-22 12:39 UTC by rephus

Closes: 

### Description:

![Screenshot from 2023-12-22 12-12-05](https://github.com/lightdash/lightdash/assets/1983672/644adc4e-343c-4cdb-9662-aa4713029734)

![Screenshot from 2023-12-22 12-12-17](https://github.com/lightdash/lightdash/assets/1983672/1ad7c0aa-208d-47ad-a382-8123cfc61b51)

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2023-12-27 09:57 UTC, joaoviana approved these changes

2023-12-27 12:06 UTC, joaoviana requested changes
On render: 

https://lightdash-pr-8392.onrender.com/generalSettings/projectManagement/3675b69e-8324-4110-bdca-059031aa8da3/projectAccess

When I'm logged in as `Viewer` I can't see the download icon on the view chart section, and also on the results table... What am I doing wrong?
<img width="1512" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/fc29be09-a805-470b-a681-91602dd70ae3">

2024-01-04 08:44 UTC, rephus commented
@joaoviana 

I'm not sure, :thinking: you can try loggin in with an existing viewer account, like: 

demo+member-1703250221691@lightdash.com (he is a member in the org, a viewer in the project)
test1234


![Screenshot from 2024-01-04 09-38-59](https://github.com/lightdash/lightdash/assets/1983672/7b6f1e70-5149-4011-bc2e-0ba24f63295c)

2024-01-04 14:37 UTC, joaoviana approved these changes
Works great!

2024-01-04 14:37 UTC, merged