feat: single selection filter in dashboard filters
lightdash/lightdash pull request #8446
Opened 2024-01-01 07:07 UTC by jogeshwar01

Closes: #8138 

### Description:
Added an `EQUALS_ONLY` FilterOperator

There are basically 2 main types for which we would need this – `STRING` and `NUMBER`.
For these, I have kept the backend same ie. using the IN clause in sql, just that now we would have a single element array when EQUALS_ONLY is selected.

For the frontend,
the numbers can directly use our `FilterNumberInput` which accepts a simple `NumberInput`.

In strings, for cases (like EQUALS, NOT_EQUALS etc), we use the components `FilterStringAutoComplete` and `FilterMultiStringInput` depending on whether it `isTableCalculationField`.
Modifying both of these components was also an alternative here (but that might have made the logic more complex)

So, I have added a new component `FilterSingleStringAutoComplete` as this felt a lot cleaner to me.
This handles both cases - Normal as well as TableCalculationFields using a flag. 
Here we would have a Select rather than a Multi-Select

I have also added some logic in useEffect to handles option changes from multiple to single inputs.
This is useful when a user has selected lets say 3 inputs (in `is` option) and then switches to `is_only` option. Then we update the value with the first element of the input. I do think there will be an optimised way to do this. Would love to discuss this.

Here are some screenshots of the output,

Strings -
![image](https://github.com/lightdash/lightdash/assets/85165953/d20d804e-cb0e-43df-aea7-07306f6b6bdc)

![image](https://github.com/lightdash/lightdash/assets/85165953/fec2fd0c-d47f-41b4-8ec7-0ef0c28891fb)

Numbers -
![image](https://github.com/lightdash/lightdash/assets/85165953/8d7be201-303e-4222-a868-cd90526fd2a3)

![image](https://github.com/lightdash/lightdash/assets/85165953/27ab4a16-dee6-460d-9c8a-ccb61b266671)

Combination - 
![image](https://github.com/lightdash/lightdash/assets/85165953/fb827341-bf46-4178-8e9b-5c070dc82f6f)

![image](https://github.com/lightdash/lightdash/assets/85165953/a6f0651f-429a-4c52-b240-e1b905d3bc5a)

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-01-10 11:08 UTC, joaoviana commented on packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
> +                case FilterType.STRING:
perhaps this (and the case in 115) can be moved to its own `case`? I think it's a bit confusing 🤔

2024-01-11 18:36 UTC, joaoviana commented on packages/frontend/src/components/common/Filters/FilterInputs/DefaultFilterInputs.tsx
> +                case FilterType.STRING:
Thank you @jogeshwar01 for the prompt push. I will review this locally and with a duplicate PR to test e2es :)

2024-01-11 18:52 UTC, joaoviana requested changes
Looks great @jogeshwar01 !!

I've tested so far: 
* Charts + filters
* Dashboard + saved filters + temporary filters + overrides + exports + scheduled deliveries (send now and scheduled)

Could you add this change?

In: packages/frontend/src/components/DashboardFilter/FilterConfiguration/utils/index.ts

<img width="1868" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/45151492-164a-46b0-b79e-3aa244c38e88">

2024-01-11 18:55 UTC, joaoviana commented
One for maybe @TuringLovesDeathMetal 
I add filter with value `x` with the `is only` operator
I try to add temporary filter with value `y` with the `is only` operator as well
It doesn't let me choose the other values. 

<img width="940" alt="image" src="https://github.com/lightdash/lightdash/assets/7611706/3fb91309-fc96-4265-abff-53950b3329e3">

Expected? I think so, makes sense

2024-01-11 19:04 UTC, jogeshwar01 commented
> Could you add this change?
> 
> In: packages/frontend/src/components/DashboardFilter/FilterConfiguration/utils/index.ts

@joaoviana 
Ah, I shouldn't have missed that. Thanks for pointing it out.
I have added this change.

2024-01-12 09:21 UTC, TuringLovesDeathMetal commented
Yep, that behaviour makes sense to me!

2024-01-12 13:27 UTC, joaoviana commented
Hi @jogeshwar01 , thanks so much for the contribution on this issue. 
We've discussed this internally, and although an operator like `is only` would allow for single selection filtering, we believe that the current `equals/is` filter type input should be extended/reworked to allow only single selection. This requires a bit of thinking with Product, Design, and other customers/users. 
Unfortunately I have to close this PR.

2024-01-12 13:27 UTC, closed without merging

2024-01-12 19:36 UTC, jogeshwar01 commented
@joaoviana Appreciate the review. I'm on board with adjusting the current equals/is filter input for single selection. I'll be happy to contribute on this once the proposal is finalized.