chore: use bookworm-slim for docker base image
lightdash/lightdash pull request #8648
Opened 2024-01-18 14:13 UTC by owlas

Closes: 

### Description:

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-01-19 10:28 UTC, rephus commented
running tests

2024-01-19 10:30 UTC, rephus requested changes
We also need to update dockerfile-prs file

2024-01-19 10:33 UTC, rephus commented
I've manually created a new project snowflake + github 

https://lightdash-pr-8648.onrender.com/projects/a646fe0e-220b-4a10-9d88-59d06fabdd30/tables/payments?

2024-01-22 09:03 UTC, rephus commented
I got this error when trying to create a project 

![image](https://github.com/lightdash/lightdash/assets/1983672/d030887e-5101-4194-ac6d-e99907e7f082)

I installed git-all from apt

2024-01-22 09:34 UTC, rephus commented
Fixed the git issue

We also need to install git on stage 3 

![image](https://github.com/lightdash/lightdash/assets/1983672/3dbf3686-9b3d-4d51-9ed1-252549c001dd)

2024-01-22 09:46 UTC, rephus commented on dockerfile-prs
> +RUN python3 -m venv /usr/local/dbt1.4 \
copy how we do it on `dockerfile`

2024-01-22 14:54 UTC, owlas commented
Works well with bigquery + CLI workflow

2024-01-22 15:02 UTC, rephus approved these changes

2024-01-22 15:04 UTC, merged