feat: export png by default
lightdash/lightdash pull request #8908
Opened 2024-02-12 19:30 UTC by jogeshwar01

Closes: #8906 

### Description:

- Set `png` as the default export option in charts
- Allow the toggling of background transparency in `png` - set transparent by default
- I have added select options `Transparent` and `Opaque` for png exports. We can change the values to whatever feels suitable. Can also create an enum for the transparency options similar to how its done for download type if need be.

Output - 

`bg-transparency option in png` - 

![image](https://github.com/lightdash/lightdash/assets/85165953/a4b3acab-eb0c-470b-84eb-a9eb5c953a1e)

Transparent PNG -

![image](https://github.com/lightdash/lightdash/assets/85165953/8c2c444e-526f-46a7-96b5-0a9cd7d84074)

Opaque PNG - 

![image](https://github.com/lightdash/lightdash/assets/85165953/e17b461a-c6fb-4676-9994-0e8d268d333f)

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-02-13 13:06 UTC, joaoviana requested changes
Thanks for the speedy contribution @jogeshwar01!
Minor change in requirements: 
* `opaque` is set by default
* use `SegmentedControl` instead of a `Select`

Thanks!

2024-02-13 13:06 UTC, joaoviana commented on packages/frontend/src/components/ChartDownload.tsx
> +
https://v6.mantine.dev/core/segmented-control/

Could we use a `Segmented Control` where `opaque` is the default? 

Just made the change to the original ticket 👍

2024-02-13 13:06 UTC, joaoviana commented on packages/frontend/src/components/ChartDownload.tsx
> +                    (type === 'png' && !backgroundTransparent)
```suggestion
                    (type === 'png' && !isBackgroundTransparent)
```

2024-02-13 15:13 UTC, jogeshwar01 commented
@joaoviana Pushed the suggested changes.

Here is the `Segmented Control` - 

![image](https://github.com/lightdash/lightdash/assets/85165953/e28ce41f-32d4-4955-8ac1-66cce38c8c17)

2024-02-14 09:18 UTC, joaoviana approved these changes

2024-02-14 09:18 UTC, merged