docs: removes dbt metrics docs
lightdash/lightdash pull request #9012
Opened 2024-02-20 11:22 UTC by TuringLovesDeathMetal

Removes dbt metrics docs and replaces with reference to Semantic Layer.

2024-02-21 15:17 UTC, hamzahc1 requested changes

2024-02-21 15:17 UTC, hamzahc1 commented on docs/docs/references/metrics.mdx
> +2. [Using dbt's Semantic Layer](#using-dbts-semantic-layer)
Should we add a beta tag here so folks know it's not a GA feature?

2024-02-23 11:19 UTC, ZeRego approved these changes

2024-02-26 09:39 UTC, hamzahc1 requested changes

2024-02-26 09:39 UTC, hamzahc1 commented on docs/docs/references/metrics.mdx
> +2. [Using dbt's Semantic Layer](#using-dbts-semantic-layer) (this is still a Beta feature)
Can you update the text in parenthesis to: "(This integration is in public beta in Lightdash)"

2024-02-26 09:53 UTC, TuringLovesDeathMetal commented on docs/docs/references/metrics.mdx
> +2. [Using dbt's Semantic Layer](#using-dbts-semantic-layer) (this is still a Beta feature)
```suggestion
2. [Using dbt's Semantic Layer](#using-dbts-semantic-layer) (this integration is in public beta in Lightdash)
```

2024-02-26 09:55 UTC, hamzahc1 approved these changes

2024-02-26 10:13 UTC, merged