fix: delete property of columnProperties object
lightdash/lightdash pull request #9061
Opened 2024-02-21 20:21 UTC by jogeshwar01

Closes: #9027 

### Description:

I have utilized cloneDeep to create a fully independent copy of the columnProperties object, avoiding the direct mutation of state. 
Also each property is checked for configurability before deletion, to prevent deletion of non-configurable properties.

Had to create a test object to reproduce the issue,

Test object :

```
let properties = {};

Object.defineProperties(properties, {
            __1: {
                value: { visible: true, name: 'Column 1', frozen: false },
                configurable: false,
                enumerable: true,
            },
            column2: {
                value: { visible: true, name: 'Column 2', frozen: false },
                configurable: true, 
                enumerable: true,
            },
        });
 ```

-  Here, column2 is deleted without issues, but while deleting column __1, we get error - 

![image](https://github.com/lightdash/lightdash/assets/85165953/63fd6584-b2f6-494a-acc9-af978e2f5711)

- Added check for configurable solves this.

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-02-27 14:13 UTC, owlas requested changes
This would be safer not to use `delete` so we don't hit this bug again. It's good that this makes a copy of the state rather than modifying it, but we can get away with a shallow copy, since we're not modifying nested states.

For example

```
            setColumnProperties(
                Object.keys(columnProperties).reduce(
                    (acc, field) =>
                        selectedItemIds.includes(field)
                            ? {
                                  ...acc,
                                  [field]: columnProperties[field],
                              }
                            : acc,
                    {},
                ),
            );
```

2024-02-27 17:16 UTC, jogeshwar01 commented
@owlas
Thanks for the review. I've updated the code to use `reduce` instead.

2024-02-28 09:38 UTC, owlas commented
/duplicate-external-pr

2024-03-06 10:11 UTC, owlas approved these changes

2024-03-06 10:11 UTC, merged