refractor: Update types from 'any' to 'unknown' in some files
lightdash/lightdash pull request #9161
Opened 2024-02-29 05:36 UTC by Inder782

Closes: 

### Description:

Tried to refactor the code by changing some types from `any` to `unknown`. I made these changes incrementally to get feedback on whether I am moving in the right direction. I'll proceed or adjust my approach based on the feedback received.

![Refactor](https://github.com/lightdash/lightdash/assets/124162738/6a51fca8-059a-4ed4-a708-3d8176afa4d7)

### Reviewer Actions

- [ ] I have manually tested the changes in the preview environment.
- [ ] I have reviewed the code.
- [ ] I understand that "request changes" will block this PR from merging.

2024-02-29 10:49 UTC, ZeRego commented
@Inder782 this is in the right direction 👍 linting seems to be failing. There are `fix-format` and `fix-linting` commands to help with this.

2024-02-29 11:57 UTC, ZeRego requested changes
Needs to pass build/test check

2024-03-01 13:32 UTC, Inder782 commented
Thanks for the feedback, @ZeRego. I'll use fix-formatting and fix-linting, and then I'll also refactor the entire frontend folder for the first pull request. After that, I'll move forward.

2024-03-04 10:02 UTC, ZeRego commented on packages/frontend/src/hooks/echarts/useEchartsCartesianConfig.ts
> +            // If using shared chart colors, we don't specify unknown colors at the top level,
```suggestion
            // If using shared chart colors, we don't specify any colors at the top level,
```

2024-03-05 17:42 UTC, ZeRego commented
Closing this PR, feel free to reopen when fixes are ready 👍

2024-03-05 17:42 UTC, closed without merging