feat: export dashboard csv
lightdash/lightdash pull request #9604
Opened 2024-04-02 09:37 UTC by rephus

Closes: #9482

### Description:

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-04-03 09:51 UTC, rephus commented on packages/frontend/src/components/common/modal/DashboardExportModal.tsx
> +    const dashboardFilters: SchedulerFilterRule[] | undefined = [];
I still need to get the `current` dashboard filters to send it to the backend, in the image we use the location, but we can't use a plain string here, any ideas @joaoviana  ?

2024-04-03 09:51 UTC, rephus commented on packages/backend/src/services/CsvService/CsvService.ts
> +        queryFilters: SchedulerFilterRule[] | undefined,
I copied this from the `getCsvsForDashboard` ,b ut we can change it if needed

2024-04-03 09:52 UTC, rephus commented
This method runs in the API , not in scheduler, this should be ok, as long as we only get results from the `table` and not `all`, if we change this option we'll need to move it to the scheduler to avoid blocking the API

2024-04-03 10:09 UTC, TuringLovesDeathMetal approved these changes
Nice! looks great :) 

Just double checking: have we updated the analytics event for dashbaord downloads to include `csv` as a type? Also, can we update the docs please 🙏

2024-04-03 16:07 UTC, joaoviana requested changes
Looking great! 
Few requested changes 👍

2024-04-04 06:43 UTC, rephus commented on packages/frontend/src/components/common/modal/DashboardExportModal.tsx
> +                        opened={true}
mmm, we do if we take `& ModalProps` in the component

2024-04-04 07:11 UTC, rephus commented
@joaoviana thanks, that worked, 
![Screenshot from 2024-04-04 08-56-37](https://github.com/lightdash/lightdash/assets/1983672/33b132f2-fcbc-4231-b705-5b192b8b542f)

Before:

![Screenshot from 2024-04-04 08-56-08](https://github.com/lightdash/lightdash/assets/1983672/20022540-d617-44b5-90fd-4b5d044c22ab)

After:

![Screenshot from 2024-04-04 09-04-08](https://github.com/lightdash/lightdash/assets/1983672/ec7a08e3-00fd-4e85-83c4-ee7535ab975b)

2024-04-04 08:32 UTC, joaoviana approved these changes
🎉

2024-04-04 09:53 UTC, merged