fix: The tab delete modal should be more explicit about which tiles/c…
lightdash/lightdash pull request #9878
Opened 2024-04-24 15:31 UTC by Shifan-Gu

…harts you will delete

Closes: 
[](https://github.com/lightdash/lightdash/issues/9870)

1. when there's saved charts that only belongs to dashboard

<img width="871" alt="Screenshot 2024-04-24 at 13 23 42" src="https://github.com/lightdash/lightdash/assets/101873365/7be2ac2e-f072-4338-854d-f16262303f8b">

2. when there's no saved chart created within dashboard

<img width="842" alt="Screenshot 2024-04-24 at 13 23 57" src="https://github.com/lightdash/lightdash/assets/101873365/a7aac002-6090-476a-a215-46c7650a7f12">

3. when tab has no tiles it will just delete the tab without open the modal

### Description:

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-04-25 14:13 UTC, rephus approved these changes
Reviewed and tested locally

2024-04-25 14:47 UTC, rephus requested changes
There is an error in a test, I tested it manually too. 

I can't create save a dashboard with a chart in dashboard. See video:

[Screencast from 25-04-24 16:46:28.webm](https://github.com/lightdash/lightdash/assets/1983672/32285b1e-a23d-453f-9e3d-3145e937a2d8)

2024-04-25 15:13 UTC, Shifan-Gu commented
Hi @rephus, thank you for the review! i'v put a fix for the issue.

2024-04-26 12:15 UTC, rephus approved these changes

2024-04-26 12:15 UTC, merged