Feat promote charts
lightdash/lightdash pull request #9895
Opened 2024-04-26 12:10 UTC by rephus

Closes: https://github.com/lightdash/lightdash/issues/9855

### Description:

### Reviewer actions

- [ ] I have manually tested the changes in the preview environment
- [ ] I have reviewed the code
- [ ] I understand that "request changes" will block this PR from merging

2024-05-01 07:06 UTC, rephus commented
This PR depends on https://github.com/lightdash/lightdash/pull/9875, merge that one first to make this easier to review

2024-05-01 14:22 UTC, owlas commented on packages/frontend/src/components/DataOps/hooks/useUpstreamProject.ts
> +                await queryClient.invalidateQueries(['project', id]);
actually after testing this works well in the FE

2024-05-01 14:29 UTC, owlas commented on packages/backend/src/services/ProjectService/ProjectService.ts
> +                await checkPermissions(
We should check if the user has access to create spaces in the upstream uproject

2024-05-01 14:31 UTC, owlas commented on packages/backend/src/services/ProjectService/ProjectService.ts
> +            const updatedChart = await this.savedChartModel.createVersion(
we should include name + description

2024-05-06 07:24 UTC, rephus commented on packages/backend/src/services/ProjectService/ProjectService.ts
> +    async updateMetadata(
done, I replaced this with `null` if we want to `unset` this . Undefined on knex by default ignores the field in `update`

2024-05-06 07:41 UTC, rephus commented on packages/backend/src/services/DashboardService/DashboardService.test.ts
> -        expect(dashboardModel.create).toHaveBeenCalledTimes(1);
reverted

2024-05-07 10:00 UTC, owlas requested changes
Code looks good but got this when promoting:

![CleanShot 2024-05-07 at 10 59 44@2x](https://github.com/lightdash/lightdash/assets/11660098/b58a89c5-31e8-46a9-90b6-1ae693c6e10d)

2024-05-07 13:41 UTC, rephus commented
> Code looks good but got this when promoting:

Fixed error message 

![Screenshot from 2024-05-07 15-38-13](https://github.com/lightdash/lightdash/assets/1983672/99988cb3-698f-40e9-919f-df2e45c4dc8c)



tl;dr, we should never use `throw new Error` in the backend.

2024-05-07 13:54 UTC, owlas commented
If you want the error to show correctly @rephus it should always be a child of `LightdashError` or it'll by default get wrapped in a `LightdashUnexpectedServerError`

2024-05-07 13:54 UTC, owlas approved these changes

2024-05-07 14:33 UTC, merged